#!/usr/bin/env python3
"""
mol2step.py — Generate solid STEP/STL CAD files of ball-and-stick molecular
models from molecular geometry files (MOL/SDF, XYZ, PDB).

Atom spheres are sized by van der Waals radius. Bond tubes are sized by
the van der Waals radius of hydrogen. All primitives are fused in one
BRepAlgoAPI_Fuse call to produce a single solid BREP body.

Produces true solid BREP geometry that imports into OnShape, FreeCAD, or
any STEP-compatible CAD program.

Requirements:
    conda/mamba install -c conda-forge cadquery numpy

Usage:
    python mol2step.py molecule.mol -o molecule.step
    python mol2step.py molecule.mol --vdw-scale 0.5 --bond-scale 0.3
    python mol2step.py molecule.mol --debug   # verbose geometry validation

Scale convention (default --scale 10):
    1 Å VdW radius  →  1 cm sphere diameter
    Bond tubes sized to H VdW × bond-scale

Author: Generated by Claude for foton's molecular printing workflow
License: AGPL-3.0-or-later
"""

import argparse
import json
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np

# ═══════════════════════════════════════════════════════════════════════════
# DATA TABLES
# ═══════════════════════════════════════════════════════════════════════════

# Van der Waals radii (Å) — 96 elements, Z=1..96
# Mantina et al., J. Phys. Chem. A 2009, 113, 5806 (main group)
# Alvarez, Dalton Trans. 2013, 42, 8617 (d-block, f-block)
# Bondi, J. Phys. Chem. 1964, 68, 441 (original)
VDW_RADII = {
    "H":  1.20, "He": 1.40,
    "Li": 1.81, "Be": 1.53, "B":  1.92, "C":  1.70, "N":  1.55,
    "O":  1.52, "F":  1.47, "Ne": 1.54,
    "Na": 2.27, "Mg": 1.73, "Al": 1.84, "Si": 2.10, "P":  1.80,
    "S":  1.80, "Cl": 1.75, "Ar": 1.88,
    "K":  2.75, "Ca": 2.31,
    "Sc": 2.15, "Ti": 2.11, "V":  2.07, "Cr": 2.06, "Mn": 2.05,
    "Fe": 2.04, "Co": 2.00, "Ni": 1.97, "Cu": 1.96, "Zn": 2.01,
    "Ga": 1.87, "Ge": 2.11, "As": 1.85, "Se": 1.90, "Br": 1.83,
    "Kr": 2.02,
    "Rb": 3.03, "Sr": 2.49,
    "Y":  2.32, "Zr": 2.23, "Nb": 2.18, "Mo": 2.17, "Tc": 2.16,
    "Ru": 2.13, "Rh": 2.10, "Pd": 2.10, "Ag": 2.11, "Cd": 2.18,
    "In": 1.93, "Sn": 2.17, "Sb": 2.06, "Te": 2.06, "I":  1.98,
    "Xe": 2.16,
    "Cs": 3.43, "Ba": 2.68,
    "La": 2.43, "Ce": 2.42, "Pr": 2.40, "Nd": 2.39, "Pm": 2.38,
    "Sm": 2.36, "Eu": 2.35, "Gd": 2.34, "Tb": 2.33, "Dy": 2.31,
    "Ho": 2.30, "Er": 2.29, "Tm": 2.27, "Yb": 2.26, "Lu": 2.24,
    "Hf": 2.23, "Ta": 2.22, "W":  2.18, "Re": 2.16, "Os": 2.16,
    "Ir": 2.13, "Pt": 2.13, "Au": 2.14, "Hg": 2.23,
    "Tl": 1.96, "Pb": 2.02, "Bi": 2.07, "Po": 1.97, "At": 2.02,
    "Rn": 2.20,
    "Fr": 3.48, "Ra": 2.83,
    "Ac": 2.47, "Th": 2.45, "Pa": 2.43, "U":  2.41, "Np": 2.39,
    "Pu": 2.43, "Am": 2.44, "Cm": 2.45,
}
DEFAULT_VDW_RADIUS = 2.00

# Covalent radii (Å) for bond inference — Cordero et al., Dalton Trans. 2008
COVALENT_RADII = {
    "H":  0.31, "He": 0.28,
    "Li": 1.28, "Be": 0.96, "B":  0.84, "C":  0.76, "N":  0.71,
    "O":  0.66, "F":  0.57, "Ne": 0.58,
    "Na": 1.66, "Mg": 1.41, "Al": 1.21, "Si": 1.11, "P":  1.07,
    "S":  1.05, "Cl": 1.02, "Ar": 1.06,
    "K":  2.03, "Ca": 1.76,
    "Sc": 1.70, "Ti": 1.60, "V":  1.53, "Cr": 1.39, "Mn": 1.39,
    "Fe": 1.32, "Co": 1.26, "Ni": 1.24, "Cu": 1.32, "Zn": 1.22,
    "Ga": 1.22, "Ge": 1.20, "As": 1.19, "Se": 1.20, "Br": 1.20,
    "Kr": 1.16,
    "Rb": 2.20, "Sr": 1.95,
    "Y":  1.90, "Zr": 1.75, "Nb": 1.64, "Mo": 1.54, "Tc": 1.47,
    "Ru": 1.46, "Rh": 1.42, "Pd": 1.39, "Ag": 1.45, "Cd": 1.44,
    "In": 1.42, "Sn": 1.39, "Sb": 1.39, "Te": 1.38, "I":  1.39,
    "Xe": 1.40,
    "Cs": 2.44, "Ba": 2.15,
    "La": 2.07, "Ce": 2.04, "Pr": 2.03, "Nd": 2.01, "Pm": 1.99,
    "Sm": 1.98, "Eu": 1.98, "Gd": 1.96, "Tb": 1.94, "Dy": 1.92,
    "Ho": 1.92, "Er": 1.89, "Tm": 1.90, "Yb": 1.87, "Lu": 1.87,
    "Hf": 1.75, "Ta": 1.70, "W":  1.62, "Re": 1.51, "Os": 1.44,
    "Ir": 1.41, "Pt": 1.36, "Au": 1.36, "Hg": 1.32,
    "Tl": 1.45, "Pb": 1.46, "Bi": 1.48, "Po": 1.40, "At": 1.50,
    "Rn": 1.50,
    "Fr": 2.60, "Ra": 2.21,
    "Ac": 2.15, "Th": 2.06, "Pa": 2.00, "U":  1.96, "Np": 1.90,
    "Pu": 1.87, "Am": 1.80, "Cm": 1.69,
}
DEFAULT_COVALENT_RADIUS = 1.50
MIN_BOND_DIST = 0.4  # Å — minimum interatomic distance treated as a bond


# ═══════════════════════════════════════════════════════════════════════════
# MOLECULE DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class Atom:
    index: int
    element: str
    x: float
    y: float
    z: float

    @property
    def pos(self):
        return np.array([self.x, self.y, self.z])

    @property
    def vdw_radius(self):
        return VDW_RADII.get(self.element, DEFAULT_VDW_RADIUS)

    @property
    def covalent_radius(self):
        return COVALENT_RADII.get(self.element, DEFAULT_COVALENT_RADIUS)


@dataclass
class Bond:
    atom1_idx: int
    atom2_idx: int
    order: int = 1


@dataclass
class Molecule:
    name: str = "molecule"
    atoms: list = field(default_factory=list)
    bonds: list = field(default_factory=list)

    def center_on_origin(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        com = coords.mean(axis=0)
        for a in self.atoms:
            a.x -= com[0]; a.y -= com[1]; a.z -= com[2]

    def bounding_box(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        return coords.min(axis=0), coords.max(axis=0)



# ═══════════════════════════════════════════════════════════════════════════
# GEOMETRY HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def _bond_offsets(d_hat, order, t_r):
    """
    Return [(offset_vector, cylinder_radius)] for each strand of a bond.

    Single bond: one entry — zero offset, radius t_r.
    Multi bond:  `order` entries evenly distributed angularly around d_hat,
                 using reduced radius (t_r * 0.65) and lateral offset (t_r * 0.85).

    d_hat must be a unit numpy array along the bond axis.
    """
    if order == 1:
        return [(np.zeros(3), t_r)]
    mr = t_r * 0.65
    od = t_r * 0.85
    ref = np.array([0.0, 0.0, 1.0]) if abs(d_hat[2]) < 0.707 \
          else np.array([1.0, 0.0, 0.0])
    u   = np.cross(d_hat, ref)
    mag = np.linalg.norm(u)
    if mag < 1e-9:
        ref = np.array([0.0, 1.0, 0.0])
        u   = np.cross(d_hat, ref)
        mag = np.linalg.norm(u)
    u /= mag
    v = np.cross(d_hat, u)
    result = []
    for k in range(order):
        theta = math.pi * k if order == 2 else 2.0 * math.pi * k / order
        off = od * (math.cos(theta) * u + math.sin(theta) * v)
        result.append((off, mr))
    return result


# ═══════════════════════════════════════════════════════════════════════════
# FILE PARSERS
# ═══════════════════════════════════════════════════════════════════════════

def parse_mol_file(filepath):
    filepath = Path(filepath)
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    if len(lines) < 4:
        raise ValueError(f"{filepath}: too short to be a valid V2000 MOL file")
    mol.name = lines[0].strip() or filepath.stem
    # V2000 counts line uses fixed-width fields: cols 0-2 = atom count, 3-5 = bond count
    counts_line = lines[3]
    try:
        na, nb = int(counts_line[0:3]), int(counts_line[3:6])
    except ValueError:
        raise ValueError(f"{filepath}: malformed counts line: {counts_line!r}")
    if len(lines) < 4 + na + nb:
        raise ValueError(
            f"{filepath}: file truncated (expected {4 + na + nb} lines, got {len(lines)})")
    # V2000 atom block: cols 0-9 = x, 10-19 = y, 20-29 = z, 31-33 = element symbol
    for i in range(na):
        ln = lines[4 + i]
        try:
            x, y, z = float(ln[0:10]), float(ln[10:20]), float(ln[20:30])
            elem = ln[31:34].strip()
        except (ValueError, IndexError):
            raise ValueError(f"{filepath}: malformed atom line {4 + i + 1}: {ln!r}")
        if not elem:
            raise ValueError(f"{filepath}: empty element symbol on atom line {4 + i + 1}")
        mol.atoms.append(Atom(i, elem, x, y, z))
    # V2000 bond block: cols 0-2 = atom1, 3-5 = atom2, 6-8 = bond order
    for i in range(nb):
        ln = lines[4 + na + i]
        try:
            a1, a2, order = int(ln[0:3]), int(ln[3:6]), int(ln[6:9])
        except (ValueError, IndexError):
            raise ValueError(f"{filepath}: malformed bond line {4 + na + i + 1}: {ln!r}")
        mol.bonds.append(Bond(a1 - 1, a2 - 1, order))
    return mol


def parse_xyz_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    na = int(lines[0].strip())
    mol.name = lines[1].strip() or Path(filepath).stem
    for i in range(na):
        p = lines[2 + i].split()
        elem = p[0][0].upper() + p[0][1:].lower() if len(p[0]) > 1 else p[0].upper()
        mol.atoms.append(Atom(i, elem, float(p[1]), float(p[2]), float(p[3])))
    for i in range(na):
        for j in range(i + 1, na):
            ai, aj = mol.atoms[i], mol.atoms[j]
            d = np.linalg.norm(ai.pos - aj.pos)
            if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                mol.bonds.append(Bond(i, j))
    return mol


def _pdb_element_from_name(name_field):
    """Derive element symbol from PDB atom-name field (cols 12-16) as a fallback."""
    nm = name_field.strip()
    # Strip leading digits: "1HB", "2HD" etc. are hydrogen atoms
    nm = nm.lstrip("0123456789")
    alpha = "".join(c for c in nm if c.isalpha())[:2]
    if not alpha:
        return "X"
    if len(alpha) == 1:
        return alpha.upper()
    candidate = alpha[0].upper() + alpha[1].lower()
    # Accept two-letter symbol only if it's a known element; else fall back to one letter
    return candidate if candidate in VDW_RADII else alpha[0].upper()


def parse_pdb_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    mol = Molecule()
    mol.name = Path(filepath).stem
    serial_map = {}
    with open(filepath) as f:
        lines = f.readlines()
    idx = 0
    for line in lines:
        if line[:6].strip() in ("ATOM", "HETATM"):
            elem = line[76:78].strip()
            if not elem:
                elem = _pdb_element_from_name(line[12:16])
            mol.atoms.append(Atom(idx, elem, float(line[30:38]),
                                  float(line[38:46]), float(line[46:54])))
            serial_map[int(line[6:11])] = idx
            idx += 1
    seen = set()
    conect = False
    for line in lines:
        if line.startswith("CONECT"):
            conect = True
            parts = line[6:].split()
            if not parts:
                continue
            i1 = serial_map.get(int(parts[0]))
            if i1 is None:
                continue
            for s in parts[1:]:
                i2 = serial_map.get(int(s))
                if i2 is None:
                    continue
                k = (min(i1, i2), max(i1, i2))
                if k not in seen:
                    seen.add(k)
                    mol.bonds.append(Bond(i1, i2))
    if not conect:
        n = len(mol.atoms)
        for i in range(n):
            for j in range(i + 1, n):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))
    return mol


def load_molecule(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    ext = Path(filepath).suffix.lower()
    if ext in (".mol", ".sdf"):
        return parse_mol_file(filepath)
    elif ext == ".xyz":
        return parse_xyz_file(filepath, tol, min_bond_dist)
    elif ext == ".pdb":
        return parse_pdb_file(filepath, tol, min_bond_dist)
    elif ext in (".cjson", ".json"):
        return parse_cjson_file(filepath, tol, min_bond_dist)
    else:
        raise ValueError(f"Unsupported: {ext}. Use .mol .sdf .xyz .pdb .cjson .json")


def validate_molecule(mol):
    """
    Check for duplicate atom positions and duplicate bonds.
    Prints warnings; returns the number of problems found.
    """
    problems = 0

    # Duplicate atom positions (within 1e-4 Å)
    pos_seen = {}
    for a in mol.atoms:
        key = tuple(np.round(a.pos, 4))
        if key in pos_seen:
            print(f"  WARNING: atom {a.element}{a.index} shares position "
                  f"{key} with atom {pos_seen[key]} — coincident spheres")
            problems += 1
        else:
            pos_seen[key] = f"{a.element}{a.index}"

    # Duplicate bonds
    bond_seen = set()
    order_names = {1: "single", 2: "double", 3: "triple"}
    for b in mol.bonds:
        k = (min(b.atom1_idx, b.atom2_idx), max(b.atom1_idx, b.atom2_idx))
        if k in bond_seen:
            a1 = mol.atoms[b.atom1_idx]
            a2 = mol.atoms[b.atom2_idx]
            oname = order_names.get(b.order, f"order-{b.order}")
            print(f"  WARNING: duplicate {oname} bond "
                  f"{a1.element}[{b.atom1_idx}]-{a2.element}[{b.atom2_idx}]"
                  f" — coincident cylinders will corrupt boolean fuse")
            print(f"    {a1.element}[{b.atom1_idx}] @ "
                  f"({a1.x:.4f}, {a1.y:.4f}, {a1.z:.4f}) Å")
            print(f"    {a2.element}[{b.atom2_idx}] @ "
                  f"({a2.x:.4f}, {a2.y:.4f}, {a2.z:.4f}) Å")
            problems += 1
        else:
            bond_seen.add(k)

    return problems


def _check_geometry_singularities(mol):
    """
    Check for geometric configurations that may cause numerical issues.

    Checks performed:
    1. Planarity — via PCA eigenvalue ratio on atom coordinates.
       A planar molecule has one near-zero eigenvalue.  OCCT BRepAlgoAPI_Fuse
       is known to produce inverted face normals for exactly-planar inputs.
    2. Near-threshold bond directions — bonds where |nz| ≈ 0.707, which is
       the switching point between the two reference vectors used in
       _make_cylinder and _bond_offsets.  Not a true singularity (cross
       product is non-zero at that angle), but useful for diagnostics.

    Prints notes; does not abort.  Returns a dict of detected conditions.
    """
    coords = np.array([a.pos for a in mol.atoms], dtype=float)
    n = len(coords)
    conditions = {}

    if n < 2:
        return conditions

    # ── 1. Planarity via PCA ───────────────────────────────────────────────
    centred = coords - coords.mean(axis=0)
    cov = (centred.T @ centred) / n
    # eigvalsh returns eigenvalues in ascending order
    eigvals = np.linalg.eigvalsh(cov)
    lam_max = eigvals[2] if eigvals[2] > 0 else 1.0
    ratio = eigvals[0] / lam_max   # out-of-plane variance / in-plane variance

    if ratio < 1e-8:
        conditions['planar'] = True
        print(f"  NOTE geometry: molecule is planar "
              f"(out-of-plane PCA variance ratio {ratio:.1e}); "
              f"OCCT boolean fuse may produce inverted face normals")
    elif ratio < 1e-3:
        conditions['near_planar'] = True
        print(f"  NOTE geometry: molecule is near-planar "
              f"(out-of-plane PCA variance ratio {ratio:.1e})")

    # ── 2. Bond directions near the reference-switching threshold ──────────
    # _make_cylinder / _bond_offsets switch from Z-ref to X-ref at |nz|=0.707.
    # At that exact angle the cross product magnitude is 0.707 — not singular —
    # but bonds close to ±Z (|nz|→1) or ±XY (|nz|→0) with the wrong ref
    # chosen would give a small cross product.  Our guard below catches that;
    # we flag here for visibility.
    SWITCH = 0.707
    MARGIN = 0.02
    near_thresh = []
    for bond in mol.bonds:
        a1, a2 = mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]
        d = a2.pos - a1.pos
        length = np.linalg.norm(d)
        if length < 1e-8:
            continue
        nz = abs(d[2] / length)
        if abs(nz - SWITCH) < MARGIN:
            near_thresh.append(
                f"{a1.element}[{bond.atom1_idx}]-"
                f"{a2.element}[{bond.atom2_idx}] (|nz|={nz:.3f})"
            )
    if near_thresh:
        conditions['near_threshold_bonds'] = near_thresh
        print(f"  NOTE geometry: {len(near_thresh)} bond(s) near reference-"
              f"switching threshold (|nz|≈0.707): {', '.join(near_thresh)}")

    return conditions


# Atomic number → element symbol lookup (Z=1..96)
_Z_TO_SYMBOL = {
    1:"H", 2:"He", 3:"Li", 4:"Be", 5:"B", 6:"C", 7:"N", 8:"O",
    9:"F", 10:"Ne", 11:"Na", 12:"Mg", 13:"Al", 14:"Si", 15:"P",
    16:"S", 17:"Cl", 18:"Ar", 19:"K", 20:"Ca", 21:"Sc", 22:"Ti",
    23:"V", 24:"Cr", 25:"Mn", 26:"Fe", 27:"Co", 28:"Ni", 29:"Cu",
    30:"Zn", 31:"Ga", 32:"Ge", 33:"As", 34:"Se", 35:"Br", 36:"Kr",
    37:"Rb", 38:"Sr", 39:"Y", 40:"Zr", 41:"Nb", 42:"Mo", 43:"Tc",
    44:"Ru", 45:"Rh", 46:"Pd", 47:"Ag", 48:"Cd", 49:"In", 50:"Sn",
    51:"Sb", 52:"Te", 53:"I", 54:"Xe", 55:"Cs", 56:"Ba", 57:"La",
    58:"Ce", 59:"Pr", 60:"Nd", 61:"Pm", 62:"Sm", 63:"Eu", 64:"Gd",
    65:"Tb", 66:"Dy", 67:"Ho", 68:"Er", 69:"Tm", 70:"Yb", 71:"Lu",
    72:"Hf", 73:"Ta", 74:"W", 75:"Re", 76:"Os", 77:"Ir", 78:"Pt",
    79:"Au", 80:"Hg", 81:"Tl", 82:"Pb", 83:"Bi", 84:"Po", 85:"At",
    86:"Rn", 87:"Fr", 88:"Ra", 89:"Ac", 90:"Th", 91:"Pa", 92:"U",
    93:"Np", 94:"Pu", 95:"Am", 96:"Cm",
}


def parse_cjson_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    """
    Parse an Avogadro2 Chemical JSON (CJSON) file.

    CJSON format (https://github.com/OpenChemistry/chemicaljson):
      {
        "chemicalJson": 1,        // or "chemical json": 0 for v0
        "name": "benzene",        // optional
        "atoms": {
          "elements": {
            "number": [6, 6, ...],     // atomic numbers
            "symbols": ["C", "C", ...] // optional, v1 only
          },
          "coords": {
            "3d": [x0, y0, z0, x1, y1, z1, ...]  // flat array, 3N
          }
        },
        "bonds": {                // optional
          "connections": {
            "index": [0, 1, 1, 2, ...]  // flat pairs: [a1,b1, a2,b2, ...]
          },
          "order": [2, 1, ...]    // bond orders
        }
      }

    If bonds are absent, they are inferred from covalent radii.
    Handles both CJSON v0 (spaces in keys) and v1 (camelCase).
    """
    mol = Molecule()
    with open(filepath) as f:
        data = json.load(f)

    # Validate it's CJSON
    if "chemicalJson" not in data and "chemical json" not in data:
        # Could be a plain JSON file — check for atoms key
        if "atoms" not in data:
            raise ValueError(
                f"{filepath}: not a recognized CJSON file "
                f"(missing 'chemicalJson' key and 'atoms' object)")

    mol.name = data.get("name", Path(filepath).stem)

    # --- Parse atoms ---
    atoms_obj = data.get("atoms", {})
    elements_obj = atoms_obj.get("elements", {})

    # Atomic numbers (required)
    atomic_numbers = elements_obj.get("number", [])

    # Element symbols (optional, v1 only) — prefer these if available
    symbols = elements_obj.get("symbols", [])

    # Coordinates: flat array [x0,y0,z0, x1,y1,z1, ...]
    coords_obj = atoms_obj.get("coords", {})
    coords_3d = coords_obj.get("3d", [])

    if not coords_3d:
        raise ValueError(f"{filepath}: no 3D coordinates found in "
                         f"atoms.coords.3d")

    num_atoms = len(coords_3d) // 3
    if len(coords_3d) != num_atoms * 3:
        raise ValueError(f"{filepath}: coords.3d length {len(coords_3d)} "
                         f"is not divisible by 3")

    if atomic_numbers and len(atomic_numbers) != num_atoms:
        raise ValueError(f"{filepath}: {len(atomic_numbers)} atomic numbers "
                         f"but {num_atoms} coordinate triples")

    for i in range(num_atoms):
        x = float(coords_3d[i * 3])
        y = float(coords_3d[i * 3 + 1])
        z = float(coords_3d[i * 3 + 2])

        # Determine element symbol
        if symbols and i < len(symbols):
            elem = symbols[i]
        elif atomic_numbers and i < len(atomic_numbers):
            z_num = int(atomic_numbers[i])
            elem = _Z_TO_SYMBOL.get(z_num, f"X{z_num}")
        else:
            elem = "X"

        mol.atoms.append(Atom(i, elem, x, y, z))

    # --- Parse bonds ---
    bonds_obj = data.get("bonds", {})
    connections = bonds_obj.get("connections", {})
    bond_indices = connections.get("index", [])
    bond_orders = bonds_obj.get("order", [])

    if bond_indices:
        num_bonds = len(bond_indices) // 2
        if len(bond_indices) != num_bonds * 2:
            print(f"  Warning: bonds.connections.index length "
                  f"{len(bond_indices)} not even, truncating")

        seen = set()
        for i in range(num_bonds):
            a1 = int(bond_indices[i * 2])
            a2 = int(bond_indices[i * 2 + 1])
            order = int(bond_orders[i]) if i < len(bond_orders) else 1
            if 0 <= a1 < num_atoms and 0 <= a2 < num_atoms:
                k = (min(a1, a2), max(a1, a2))
                if k in seen:
                    at1 = mol.atoms[a1]
                    at2 = mol.atoms[a2]
                    oname = {1: "single", 2: "double", 3: "triple"}.get(order, f"order-{order}")
                    print(f"  WARNING: duplicate {oname} bond in CJSON — "
                          f"keeping first, skipping this entry")
                    print(f"    {at1.element}[{a1}] @ "
                          f"({at1.x:.4f}, {at1.y:.4f}, {at1.z:.4f}) Å")
                    print(f"    {at2.element}[{a2}] @ "
                          f"({at2.x:.4f}, {at2.y:.4f}, {at2.z:.4f}) Å")
                    continue
                seen.add(k)
                mol.bonds.append(Bond(a1, a2, order))
    else:
        # No bond info — infer from covalent radii
        for i in range(num_atoms):
            for j in range(i + 1, num_atoms):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))

    return mol


# ═══════════════════════════════════════════════════════════════════════════
# CAD PRIMITIVES — no rotation math, uses Plane-based extrusion
# ═══════════════════════════════════════════════════════════════════════════

def _make_sphere(center_mm, radius_mm):
    """Create a solid sphere at center_mm with given radius."""
    import cadquery as cq
    s = cq.Workplane("XY").sphere(radius_mm)
    return s.translate(cq.Vector(center_mm[0], center_mm[1], center_mm[2]))


def _diag_orientation(shape, label):
    """Print in-memory volume and shell orientations for a CadQuery solid."""
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_SHELL
    s = shape.wrapped
    props = GProp_GProps()
    BRepGProp.VolumeProperties_s(s, props)
    vol = props.Mass()
    print(f"  DIAG [{label}] volume={vol:+.1f} mm³")
    exp = TopExp_Explorer(s, TopAbs_SHELL)
    idx = 0
    _ORI = {0: "FORWARD", 1: "REVERSED", 2: "INTERNAL", 3: "EXTERNAL"}
    while exp.More():
        ori = _ORI.get(exp.Current().Orientation(), "?")
        print(f"  DIAG [{label}] shell[{idx}] orientation={ori}")
        idx += 1
        exp.Next()
    if idx == 0:
        print(f"  DIAG [{label}] no shells found")


def _as_solid(shape):
    """Ensure shape is a cq.Solid, unwrapping or rebuilding as needed.

    BRepAlgoAPI_Fuse always returns TopoDS_Compound.  OCCT occasionally
    wraps the result as a closed Shell rather than a Solid.
    We handle both cases:
      1. Compound contains one Solid  → unwrap directly.
      2. Compound contains zero Solids but one closed Shell
         → rebuild a Solid via BRepBuilderAPI_MakeSolid.
    """
    solids = shape.Solids()
    if len(solids) == 1:
        return solids[0]
    if len(solids) == 0:
        shells = shape.Shells()
        if len(shells) == 1:
            from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeSolid
            import cadquery as cq
            ms = BRepBuilderAPI_MakeSolid(shells[0].wrapped)
            if ms.IsDone():
                return cq.Shape.cast(ms.Solid())
    print(f"  WARNING: _as_solid: unexpected fuse result — "
          f"{len(solids)} solid(s), {len(shape.Shells())} shell(s); "
          f"returning compound as-is (output may not be a single solid)")
    return shape


def _normalize_shell_orientations(cq_shape):
    """
    Rebuild the solid so every face's effective normal points outward.

    Sequential pairwise fuse accumulates orientation flags from intermediate
    compound contexts; STEP writers cannot resolve these and mis-orient faces.

    Reference point for the outward test is determined from the face's own
    surface geometry — not from the whole-solid centroid, which can be offset
    toward dense regions of a complex molecule:
      Sphere surface  → sphere centre (radially outward is always correct)
      Cylinder surface → any point on the cylinder axis (normal is perpendicular
                         to the axis and radially outward from it)
      Other surfaces  → fall back to the solid centroid

    Any face whose effective normal (surface normal composed with the OCCT
    orientation flag) points toward the reference is reversed.  The shell and
    solid are then rebuilt from the corrected faces.
    """
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.BRep import BRep_Builder
    from OCP.BRepLProp import BRepLProp_SLProps
    from OCP.BRepAdaptor import BRepAdaptor_Surface
    from OCP.GeomAbs import GeomAbs_Sphere, GeomAbs_Cylinder
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_FACE, TopAbs_REVERSED
    from OCP.TopTools import TopTools_MapOfShape
    from OCP.TopoDS import TopoDS_Shell, TopoDS_Solid, TopoDS
    import cadquery as cq

    solid = cq_shape.wrapped

    # Fallback reference: solid centroid (used only for non-sphere/cylinder faces)
    vol_props = GProp_GProps()
    BRepGProp.VolumeProperties_s(solid, vol_props)
    cog = vol_props.CentreOfMass()
    fallback = (cog.X(), cog.Y(), cog.Z())

    # Collect deduplicated faces (TopExp_Explorer composes orientations)
    seen = TopTools_MapOfShape()
    faces = []
    exp = TopExp_Explorer(solid, TopAbs_FACE)
    while exp.More():
        f = exp.Current()
        if not seen.Contains(f):
            seen.Add(f)
            faces.append(TopoDS.Face_s(f))
        exp.Next()

    flipped = skipped = 0
    fixed_faces = []

    for face in faces:
        try:
            adaptor = BRepAdaptor_Surface(face)
            u = (adaptor.FirstUParameter() + adaptor.LastUParameter()) * 0.5
            v = (adaptor.FirstVParameter() + adaptor.LastVParameter()) * 0.5

            slp = BRepLProp_SLProps(adaptor, u, v, 1, 1e-6)
            if not slp.IsNormalDefined():
                skipped += 1
                fixed_faces.append(face)
                continue
            # BRepAdaptor_Surface already accounts for the face orientation flag:
            # slp.Normal() returns the EFFECTIVE face normal (inward for REVERSED
            # faces, outward for FORWARD faces).  Do NOT negate based on
            # face.Orientation() — that would double-negate and invert the test.
            n = slp.Normal()
            nx, ny, nz = n.X(), n.Y(), n.Z()

            # Point on the face at the UV sample
            p = adaptor.Value(u, v)
            fx, fy, fz = p.X(), p.Y(), p.Z()

            # Reference point: primitive origin, not the whole-solid centroid.
            # For sphere/cylinder the effective normal is radially outward from
            # the primitive centre when the face is correctly oriented (FORWARD).
            surf_type = adaptor.GetType()
            if surf_type == GeomAbs_Sphere:
                loc = adaptor.Sphere().Location()
                rx, ry, rz = loc.X(), loc.Y(), loc.Z()
            elif surf_type == GeomAbs_Cylinder:
                loc = adaptor.Cylinder().Location()
                rx, ry, rz = loc.X(), loc.Y(), loc.Z()
            else:
                rx, ry, rz = fallback
        except Exception:
            skipped += 1
            fixed_faces.append(face)
            continue

        # Outward test: effective normal must point away from the reference.
        dx, dy, dz = fx - rx, fy - ry, fz - rz
        if nx * dx + ny * dy + nz * dz < 0:
            fixed_faces.append(TopoDS.Face_s(face.Reversed()))
            flipped += 1
        else:
            fixed_faces.append(face)

    if flipped or skipped:
        print(f"  Orientation fix: {flipped} face(s) flipped, {skipped} skipped")

    # Rebuild solid from corrected faces
    builder = BRep_Builder()
    shell = TopoDS_Shell()
    builder.MakeShell(shell)
    for f in fixed_faces:
        builder.Add(shell, f)

    solid_out = TopoDS_Solid()
    builder.MakeSolid(solid_out)
    builder.Add(solid_out, shell)

    # Sanity check
    chk = GProp_GProps()
    BRepGProp.VolumeProperties_s(solid_out, chk)
    vol = chk.Mass()
    if vol < 0:
        print(f"  WARNING: rebuilt solid volume is negative ({vol:.1f} mm³) "
              f"— orientation fix may have misfired")

    return cq.Shape.cast(solid_out)


def _make_cylinder(start_mm, end_mm, radius_mm):
    """
    Create a solid cylinder from start_mm to end_mm using Plane-based extrusion.
    Returns None for zero-length segments.
    """
    import cadquery as cq
    start = np.asarray(start_mm, dtype=float)
    end   = np.asarray(end_mm,   dtype=float)
    direction = end - start
    length = np.linalg.norm(direction)
    if length < 1e-6:
        return None

    nv     = direction / length
    normal = cq.Vector(nv[0], nv[1], nv[2])
    origin = cq.Vector(start[0], start[1], start[2])

    # xDir must be perpendicular to normal. Use Z unless bond is near-vertical,
    # then use X.  Threshold 1/√2 guarantees cross product is non-degenerate.
    ref      = np.array([0.0, 0.0, 1.0]) if abs(nv[2]) < 0.707 else np.array([1.0, 0.0, 0.0])
    x_dir_np = np.cross(nv, ref)
    mag      = np.linalg.norm(x_dir_np)
    if mag < 1e-9:
        # Near-singular: bond is almost parallel to chosen reference.
        # This should not happen with the 0.707 threshold, but guard anyway.
        alt_ref  = np.array([0.0, 1.0, 0.0])
        x_dir_np = np.cross(nv, alt_ref)
        mag      = np.linalg.norm(x_dir_np)
        if mag < 1e-9:
            return None  # truly degenerate — cannot place cylinder
    x_dir_np /= mag
    x_dir    = cq.Vector(x_dir_np[0], x_dir_np[1], x_dir_np[2])

    plane = cq.Plane(origin=origin, normal=normal, xDir=x_dir)
    return cq.Workplane(plane).circle(radius_mm).extrude(length)


# ═══════════════════════════════════════════════════════════════════════════
# MODEL BUILDER
# ═══════════════════════════════════════════════════════════════════════════

def sphere_radius_mm(vdw_angstroms, scale, vdw_scale):
    """VdW radius → model sphere radius in mm."""
    return vdw_angstroms * vdw_scale * scale / 2.0


def tube_radius_mm(scale, bond_scale, override=None):
    """Compute bond tube radius from H VdW and scale factors."""
    if override is not None:
        return override
    return VDW_RADII["H"] * bond_scale * scale / 2.0


def _atom_r(vdw_angstroms, scale, vdw_scale, t_r):
    """Effective atom sphere radius, clamped so the sphere always protrudes past the tube."""
    return max(sphere_radius_mm(vdw_angstroms, scale, vdw_scale),
               t_r + max(0.05, t_r * 0.01))


def validate_geometry(mol, scale, vdw_scale, bond_scale,
                      tube_radius_override=None):
    """
    Validate spatial contact between all spheres and tubes.
    Pure numpy — does NOT require CadQuery.
    """
    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)

    print("\n  ── Spatial contact validation ──")
    issues = 0

    for bond in mol.bonds:
        a1, a2 = mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]
        p1, p2 = a1.pos * scale, a2.pos * scale
        d = p2 - p1
        length = np.linalg.norm(d)
        if length < 0.01:
            print(f"  !! Zero-length bond {a1.element}{bond.atom1_idx}-"
                  f"{a2.element}{bond.atom2_idx}")
            issues += 1
            continue
        d_hat = d / length

        r1 = _atom_r(a1.vdw_radius, scale, vdw_scale, t_r)
        r2 = _atom_r(a2.vdw_radius, scale, vdw_scale, t_r)

        # Cylinder goes center-to-center (no extension)
        cyl_start = p1
        cyl_end = p2
        cyl_length = length

        raw = _bond_offsets(d_hat, bond.order, t_r)
        kind_label = "single" if bond.order == 1 else None
        offsets = [(off, cr, kind_label or f"multi-k{k}")
                   for k, (off, cr) in enumerate(raw)]

        for off, cr, kind in offsets:
            for label, center, sph_r in [
                (f"{a1.element}{bond.atom1_idx}", p1, r1),
                (f"{a2.element}{bond.atom2_idx}", p2, r2),
            ]:
                axis_origin = cyl_start + off
                v = center - axis_origin
                proj = np.dot(v, d_hat)
                closest = axis_origin + proj * d_hat
                axis_dist = np.linalg.norm(center - closest)

                # For center-to-center: atom center is at proj=0 or proj=length
                # The cylinder endpoint coincides with atom center
                # Overlap = sphere extends past cylinder end along axis
                # Overlap depth along axis = sph_r (for centered bonds)
                #                          = sqrt(sph_r^2 - axis_dist^2) for offset
                if axis_dist < sph_r:
                    depth = math.sqrt(sph_r**2 - axis_dist**2)
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    # Also check sphere excess over tube
                    excess = sph_r - cr
                    status = "OK" if (in_range and excess > 0) else \
                             "TANGENT" if (in_range and excess <= 0) else \
                             "AXIS_SHORT"
                elif axis_dist < sph_r + cr:
                    depth = 0
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    status = "PARTIAL" if in_range else "MISS"
                else:
                    depth = 0
                    status = "NO_CONTACT"
                    in_range = False

                ok = status == "OK"
                if not ok:
                    issues += 1
                sym = "  " if ok else ">>"
                off_mag = np.linalg.norm(off)
                off_s = f"off={off_mag:.2f}" if off_mag > 0.01 else "ctr"
                print(f"  {sym} {a1.element}{bond.atom1_idx}-"
                      f"{a2.element}{bond.atom2_idx} -> {label}: "
                      f"ax_d={axis_dist:.3f} sph_r={sph_r:.2f} "
                      f"cyl_r={cr:.2f} proj={proj:.1f}/{cyl_length:.1f} "
                      f"depth={depth:.2f} excess={sph_r-cr:.2f} "
                      f"{off_s} {kind} [{status}]")

    if issues:
        print(f"\n  !! {issues} issues found !!")
    else:
        print(f"\n  All {len(mol.bonds)} bonds validated — "
              f"sphere_r > tube_r at every junction.")
    return issues


def build_model(mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                tube_radius_override=None,
                no_fillet=False, add_base=False, base_thickness=3.0,
                base_margin=5.0):
    """
    Build ball-and-stick molecular model as a single fused BREP solid.

    All sphere and cylinder primitives are collected into a flat list and
    fused in one BRepAlgoAPI_Fuse call (multi-tool mode).

    --no-fillet : outputs overlapping sphere+cylinder primitives as a
                  Compound (no boolean, always valid STEP).
    --union     : accepted for backward compatibility; the default path
                  always produces a single fused solid.
    """
    if not mol.atoms:
        raise ValueError("Molecule has no atoms — nothing to build.")

    import cadquery as cq
    from OCP.BRepAlgoAPI import BRepAlgoAPI_Fuse
    from OCP.TopTools import TopTools_ListOfShape

    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)

    # ── Sizing table ──────────────────────────────────────────────────────
    print(f"  Scale: {scale} mm/A  VdW: {vdw_scale}x  Bond: {bond_scale}x")
    print(f"  Tube radius: {t_r:.3f} mm")
    print()
    print(f"  {'Elem':4s}  {'sph_r':>7s}  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':4s}  {'-----':>7s}  {'-------':>8s}  {'-----':>7s}  ------")
    for elem in sorted(set(a.element for a in mol.atoms)):
        vdw = VDW_RADII.get(elem, DEFAULT_VDW_RADIUS)
        r   = _atom_r(vdw, scale, vdw_scale, t_r)
        ov  = r - t_r
        z   = math.sqrt(max(0.0, r*r - t_r*t_r))
        ang = math.degrees(math.asin(min(1.0, z / r)))
        st  = "ok" if ov >= 1.0 else ("marginal" if ov >= 0.3 else "GAP RISK")
        print(f"  {elem:4s}  {r:7.3f}  {ov:8.3f}  {ang:7.1f}  {st}")
    print()

    gap_count = 0
    for bond in mol.bonds:
        for atom in (mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]):
            if (_atom_r(atom.vdw_radius, scale, vdw_scale, t_r) - t_r) < 0.3:
                gap_count += 1
    if gap_count:
        print(f"  WARNING: {gap_count} junctions have overlap < 0.3 mm"
              f" -- reduce --bond-scale or raise --vdw-scale")
    else:
        print("  All junction overlaps >= 0.3 mm  (ok)")
    print()

    _check_geometry_singularities(mol)

    # ── Path 1: --no-fillet compound (validated, no boolean) ─────────────
    if no_fillet:
        shapes = []
        for atom in mol.atoms:
            pos = np.asarray(atom.pos * scale, dtype=float)
            shapes.append(_make_sphere(pos, _atom_r(atom.vdw_radius, scale, vdw_scale, t_r)).val())
        n_cyl = 0
        for bond in mol.bonds:
            a1 = mol.atoms[bond.atom1_idx]
            a2 = mol.atoms[bond.atom2_idx]
            p1 = np.asarray(a1.pos * scale, dtype=float)
            p2 = np.asarray(a2.pos * scale, dtype=float)
            L  = float(np.linalg.norm(p2 - p1))
            if L < 0.01:
                continue
            d = (p2 - p1) / L
            for off, cyl_r in _bond_offsets(d, bond.order, t_r):
                cyl = _make_cylinder(p1 + off, p2 + off, cyl_r)
                if cyl is not None:
                    shapes.append(cyl.val())
                    n_cyl += 1
        print(f"  Bodies: {len(mol.atoms)} spheres + {n_cyl} cylinders "
              f"(no boolean — overlapping primitives)")
        return cq.Compound.makeCompound(shapes)

    # ── Path 2: multi-tool fuse ───────────────────────────────────────────

    # Build all sphere and cylinder primitives as a flat list
    all_shapes = []

    for atom in mol.atoms:
        pos = np.asarray(atom.pos * scale, dtype=float)
        all_shapes.append(_make_sphere(pos, _atom_r(atom.vdw_radius, scale, vdw_scale, t_r)).val())

    n_cyl = 0
    for bond in mol.bonds:
        a1 = mol.atoms[bond.atom1_idx]
        a2 = mol.atoms[bond.atom2_idx]
        p1 = np.asarray(a1.pos * scale, dtype=float)
        p2 = np.asarray(a2.pos * scale, dtype=float)
        L  = float(np.linalg.norm(p2 - p1))
        if L < 0.01:
            continue
        d = (p2 - p1) / L
        for off, cyl_r in _bond_offsets(d, bond.order, t_r):
            cyl = _make_cylinder(p1 + off, p2 + off, cyl_r)
            if cyl is not None:
                all_shapes.append(cyl.val())
                n_cyl += 1

    print(f"  Primitives: {len(mol.atoms)} spheres + {n_cyl} cylinders")

    # Single multi-tool fuse: first shape is the argument, rest are tools.
    # One kernel call avoids the incremental pairwise STEP-export orientation bug.
    if len(all_shapes) == 1:
        result = all_shapes[0]
    else:
        # Sequential pairwise fuse.
        # Multi-tool mode (SetArguments/SetTools with all shapes at once)
        # produces inverted face normals for planar molecules: at z=0
        # intersection edges the dihedral angle is exactly 0° or 180°,
        # making the ± face-classification sign ambiguous.  Pairwise fuse
        # resolves each pair in isolation and avoids the global sign flip.
        # Sequential pairwise fuse.
        # Multi-tool mode (SetArguments/SetTools with all shapes at once)
        # produces inverted face normals for planar molecules: at z=0
        # intersection edges the dihedral angle is exactly 0° or 180°,
        # making the ± face-classification sign ambiguous.  Pairwise fuse
        # resolves each pair in isolation and avoids the global sign flip.
        #
        # _as_solid is called once at the end, not inside the loop:
        # calling it on each intermediate result can corrupt later steps if
        # a non-overlapping pair produces a temporary compound.
        print(f"  Fusing {len(all_shapes)} primitives (sequential pairwise)...")
        result = all_shapes[0]
        failed = 0
        for shape in all_shapes[1:]:
            arg  = TopTools_ListOfShape(); arg.Append(result.wrapped)
            tool = TopTools_ListOfShape(); tool.Append(shape.wrapped)
            fuser = BRepAlgoAPI_Fuse()
            fuser.SetArguments(arg)
            fuser.SetTools(tool)
            fuser.SetFuzzyValue(1e-6)
            fuser.Build()
            if fuser.IsDone():
                stepped = cq.Shape.cast(fuser.Shape())
                # Unwrap compound→solid without orientation correction mid-loop
                solids = stepped.Solids()
                result = solids[0] if len(solids) == 1 else stepped
            else:
                failed += 1

        result = _as_solid(result)
        _diag_orientation(result, "after_fuse")
        if failed:
            print(f"  WARNING: {failed} pairwise fuse step(s) failed — "
                  f"result may be incomplete")
        print(f"  Fuse complete: {len(result.Faces())} faces, "
              f"{len(result.Edges())} edges")

    # ── Optional base plate ────────────────────────────────────────────────
    if add_base:
        max_r = max(_atom_r(a.vdw_radius, scale, vdw_scale, t_r) for a in mol.atoms)
        bb_min, bb_max = mol.bounding_box()
        bmin = np.asarray(bb_min * scale, dtype=float)
        bmax = np.asarray(bb_max * scale, dtype=float)
        z_bot = float(bmin[2]) - max_r - 0.5
        w  = float(bmax[0] - bmin[0]) + 2 * base_margin + 2 * max_r
        dd = float(bmax[1] - bmin[1]) + 2 * base_margin + 2 * max_r
        cx = float(bmin[0] + bmax[0]) / 2.0
        cy = float(bmin[1] + bmax[1]) / 2.0
        base_wp = (cq.Workplane("XY")
                   .box(w, dd, base_thickness)
                   .translate(cq.Vector(cx, cy, z_bot - base_thickness / 2.0)))
        try:
            base_wp = base_wp.edges("|Z").fillet(base_thickness * 0.4)
        except Exception:
            pass
        base_solid = base_wp.val()
        base_args  = TopTools_ListOfShape()
        base_args.Append(result.wrapped)
        base_tools = TopTools_ListOfShape()
        base_tools.Append(base_solid.wrapped)
        bf = BRepAlgoAPI_Fuse()
        bf.SetArguments(base_args)
        bf.SetTools(base_tools)
        bf.Build()
        if bf.IsDone():
            result = _as_solid(cq.Shape.cast(bf.Shape()))
        else:
            return cq.Compound.makeCompound([result, base_solid])

    return result


# Sphere-surface sample directions: 6 cardinal + 8 octant = 14 points
_SPHERE_SAMPLE_DIRS = [
    (1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1),
    ( 0.577,  0.577,  0.577), (-0.577,  0.577,  0.577),
    ( 0.577, -0.577,  0.577), ( 0.577,  0.577, -0.577),
    (-0.577, -0.577,  0.577), (-0.577,  0.577, -0.577),
    ( 0.577, -0.577, -0.577), (-0.577, -0.577, -0.577),
]


def _load_step_occ(step_file):
    """
    Load a STEP file using STEPControl_Reader and return the raw OCC TopoDS_Shape.

    cq.importers.importStep() has a shape-tree traversal quirk that returns
    0 solids for fused output even when the file is geometrically correct.
    This function bypasses the CadQuery wrapper entirely.

    Returns (shape, error_str); shape is None on failure.
    """
    from OCP.STEPControl import STEPControl_Reader
    from OCP.IFSelect import IFSelect_RetDone

    reader = STEPControl_Reader()
    status = reader.ReadFile(str(step_file))
    if status != IFSelect_RetDone:
        return None, f"STEPControl_Reader.ReadFile returned status {int(status)}"
    reader.TransferRoots()
    shape = reader.OneShape()
    if shape.IsNull():
        return None, "STEP file read but resulting shape is null"
    return shape, None


def _topo_explore(occ_shape, topo_type):
    """
    Return a deduplicated list of all sub-shapes of topo_type via TopExp_Explorer.
    Uses TopTools_MapOfShape to avoid counting shared sub-shapes twice.
    """
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopTools import TopTools_MapOfShape

    seen = TopTools_MapOfShape()
    exp  = TopExp_Explorer(occ_shape, topo_type)
    shapes = []
    while exp.More():
        s = exp.Current()
        if not seen.Contains(s):
            seen.Add(s)
            shapes.append(s)
        exp.Next()
    return shapes


def check_step_gaps(step_file, mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                    tube_radius_override=None):
    """
    Analytical junction geometry check against a STEP file.

    Computes sphere-tube overlap and junction angle for every bond endpoint
    directly from the model parameters -- no point-in-solid probing needed.

    overlap  = sphere_radius - tube_radius
               (how deeply the tube is embedded in the sphere)
    angle    = arcsin(sqrt(sphere_r^2 - tube_r^2) / sphere_r)
               (the angle between the bond axis and the sphere surface
                at the junction circle; 90deg = ideal, 0deg = tangent)

    Both metrics are purely geometric and computed instantly.  The STEP
    file is loaded only to verify that the expected number of hub bodies
    is present.

    Flags:
      GAP      -- overlap < 0.3 mm  OR  angle < 10 deg
      MARGINAL -- overlap < 1.0 mm  OR  angle < 20 deg
    """
    import cadquery as cq

    print("=" * 70)
    print(f"JUNCTION GEOMETRY CHECK  ({step_file})")
    print("=" * 70)

    # Load STEP and count bodies
    compound = None
    try:
        compound = cq.importers.importStep(str(step_file))
        n_bodies = len(compound.solids().vals())
        print(f"  STEP solid bodies: {n_bodies}")
    except Exception as exc:
        print(f"  Could not load STEP file: {exc}")

    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)

    print(f"  Tube radius: {t_r:.3f} mm")
    print()
    print(f"  {'Bond':22s}  {'end':>3s}  {'sph_r':>7s}"
          f"  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':22s}  {'---':>3s}  {'-----':>7s}"
          f"  {'-------':>8s}  {'-----':>7s}  ------")

    flags = []

    for bond in mol.bonds:
        a1    = mol.atoms[bond.atom1_idx]
        a2    = mol.atoms[bond.atom2_idx]
        r1, r2 = _atom_r(a1.vdw_radius, scale, vdw_scale, t_r), _atom_r(a2.vdw_radius, scale, vdw_scale, t_r)
        label  = f"{a1.element}{bond.atom1_idx}-{a2.element}{bond.atom2_idx}"

        for atom, r, end_lbl in [(a1, r1, "a1"), (a2, r2, "a2")]:
            if t_r >= r:
                print(f"  {label:22s}  {end_lbl:>3s}  DEGENERATE: tube_r >= sphere_r")
                flags.append((label, end_lbl, 0.0, 0.0, "GAP"))
                continue

            ov  = r - t_r
            z   = math.sqrt(r * r - t_r * t_r)
            ang = math.degrees(math.asin(min(1.0, z / r)))

            if ov < 0.3 or ang < 10.0:
                status = "GAP"
            elif ov < 1.0 or ang < 20.0:
                status = "MARGINAL"
            else:
                status = "ok"

            mark = "  <--" if status != "ok" else ""
            print(f"  {label:22s}  {end_lbl:>3s}  {r:7.3f}"
                  f"  {ov:8.3f}  {ang:7.1f}  {status}{mark}")

            if status != "ok":
                flags.append((label, end_lbl, ov, ang, status))

    print()
    if flags:
        print(f"  {len(flags)} junction(s) flagged:")
        for lbl, end, ov, ang, st in flags:
            print(f"    {lbl} ({end}):  overlap={ov:.3f} mm"
                  f"  angle={ang:.1f} deg  [{st}]")
    else:
        print("  All junctions ok.")

    # --- Spatial atom-presence check ---
    print()
    print("  ATOM PRESENCE CHECK")
    if compound is None:
        print("  (STEP file not loaded — skipped)")
    elif n_bodies <= 1 and len(mol.atoms) > 1:
        print("  (single fused solid — centroid-per-atom matching not applicable)")
    else:
        try:
            from OCP.BRepGProp import BRepGProp
            from OCP.GProp import GProp_GProps

            centroids = []
            for solid in compound.solids().vals():
                props = GProp_GProps()
                BRepGProp.VolumeProperties_s(solid.wrapped, props)
                c = props.CentreOfMass()
                centroids.append(np.array([c.X(), c.Y(), c.Z()]))

            centres_arr = np.array(centroids) if centroids else np.zeros((0, 3))
            THRESHOLD_MM = 0.5
            missing = []
            for atom in mol.atoms:
                expected_pos = np.asarray(atom.pos * scale, dtype=float)
                if len(centres_arr) == 0:
                    dist = float("inf")
                else:
                    dist = float(np.min(
                        np.linalg.norm(centres_arr - expected_pos, axis=1)))
                if dist > THRESHOLD_MM:
                    missing.append((atom.index, atom.element, dist,
                                    expected_pos))

            if missing:
                print(f"  WARNING: {len(missing)} atom(s) have no solid within "
                      f"{THRESHOLD_MM} mm of their expected position:")
                print(f"  {'Atom':10s}  {'nearest_mm':>10s}  expected_pos (mm)")
                for idx, elem, dist, epos in missing:
                    print(f"  {elem+str(idx):10s}  {dist:10.2f}  "
                          f"({epos[0]:.2f}, {epos[1]:.2f}, {epos[2]:.2f})")
            else:
                print(f"  All {len(mol.atoms)} atoms present.  (ok)")
        except Exception as exc:
            print(f"  Atom presence check failed: {exc}")

    print("=" * 70)


def check_final_output(step_file, mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                       tube_radius_override=None):
    """
    Comprehensive post-build validation of a STEP file.

    Loads the file via STEPControl_Reader (not the CadQuery wrapper, which
    misreports 0 solids for fused output).  Eight checks are run:

      1. Solid count       — exactly 1 solid in the file
      2. Shell count       — exactly 1 shell on that solid (single closed body)
      3. BRepCheck         — OCCT topology validity
      4. Free edges        — 0 free edges (watertight)
      5. Volume bounds     — positive volume within expected [min_sphere, sum_primitives] range
      6. Atom centers      — every atom center is inside or on the solid
      7. Sphere surfaces   — 14-direction sampling at 95 % radius detects shaved/missing
                             sphere regions that a boolean failure can produce
      8. Bounding box      — solid extents match expected atom-sphere envelope

    Returns True if no FATAL issues were found.
    """
    import math
    from OCP.TopAbs import (TopAbs_SOLID, TopAbs_SHELL, TopAbs_FACE,
                             TopAbs_IN, TopAbs_ON, TopAbs_OUT)
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.BRepClass3d import BRepClass3d_SolidClassifier
    from OCP.gp import gp_Pnt
    from OCP.ShapeAnalysis import ShapeAnalysis_ShapeContents
    from OCP.BRepCheck import BRepCheck_Analyzer
    from OCP.Bnd import Bnd_Box
    from OCP.BRepBndLib import BRepBndLib

    print("=" * 70)
    print(f"FINAL OUTPUT CHECK  ({step_file})")
    print("=" * 70)

    # ── Load STEP ─────────────────────────────────────────────────────────
    occ_shape, err = _load_step_occ(step_file)
    if occ_shape is None:
        print(f"  FATAL: cannot load STEP: {err}")
        print("=" * 70)
        return False

    t_r    = tube_radius_mm(scale, bond_scale, tube_radius_override)
    fatal  = []
    warns  = []

    # ── Check 1: solid count ──────────────────────────────────────────────
    solids = _topo_explore(occ_shape, TopAbs_SOLID)
    shells = _topo_explore(occ_shape, TopAbs_SHELL)
    faces  = _topo_explore(occ_shape, TopAbs_FACE)
    print(f"  Topology: {len(solids)} solid(s)  "
          f"{len(shells)} shell(s)  {len(faces)} face(s)")

    if len(solids) == 0:
        fatal.append("NO_SOLID: no solid bodies found in STEP file")
        print(f"\n  RESULT: FAIL — {len(fatal)} fatal issue(s)")
        print("=" * 70)
        return False

    if len(solids) > 1:
        fatal.append(f"MULTI_SOLID: {len(solids)} separate bodies — "
                     f"fuse did not produce a single solid")
    else:
        print(f"  Single solid: YES")

    solid_shape = solids[0]

    # ── Check 2: shell count ──────────────────────────────────────────────
    solid_shells = _topo_explore(solid_shape, TopAbs_SHELL)
    n_shells = len(solid_shells)
    if n_shells == 1:
        print(f"  Shell count: 1 — single closed body (ok)")
    else:
        fatal.append(f"SHELL_COUNT: {n_shells} shells (expected 1 for a properly "
                     f"fused solid; extra shells indicate disconnected regions)")

    # ── Check 3: BRepCheck_Analyzer ───────────────────────────────────────
    try:
        ana = BRepCheck_Analyzer(solid_shape, True)
        if ana.IsValid():
            print(f"  BRepCheck: valid")
        else:
            fatal.append("BREP_INVALID: BRepCheck_Analyzer reports invalid topology")
    except Exception as exc:
        warns.append(f"BREP_CHECK_ERROR: {exc}")

    # ── Check 4: free edges ───────────────────────────────────────────────
    try:
        contents = ShapeAnalysis_ShapeContents()
        contents.Perform(solid_shape)
        free_edges = contents.NbFreeEdges()
        if free_edges == 0:
            print(f"  Free edges: 0 — watertight (ok)")
        else:
            fatal.append(f"FREE_EDGES: {free_edges} free edge(s) — "
                         f"solid is not watertight; slicing will likely fail")
    except Exception as exc:
        warns.append(f"FREE_EDGE_CHECK_ERROR: {exc}")

    # ── Check 5: volume bounds ────────────────────────────────────────────
    vol = None
    try:
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(solid_shape, props)
        vol = props.Mass()

        # Upper bound: sum of all primitive volumes (no overlap removed)
        sphere_vols = sum(
            (4.0 / 3.0) * math.pi * _atom_r(a.vdw_radius, scale, vdw_scale, t_r) ** 3
            for a in mol.atoms
        )
        cyl_vols = 0.0
        for bond in mol.bonds:
            a1 = mol.atoms[bond.atom1_idx]
            a2 = mol.atoms[bond.atom2_idx]
            seg = (a2.pos - a1.pos) * scale
            L   = float(np.linalg.norm(seg))
            if L > 0:
                d_hat = seg / L
                for _off, cyl_r in _bond_offsets(d_hat, bond.order, t_r):
                    cyl_vols += math.pi * cyl_r ** 2 * L

        # Lower bound: at least the largest single sphere must survive
        max_r   = max(_atom_r(a.vdw_radius, scale, vdw_scale, t_r) for a in mol.atoms)
        vol_min = (4.0 / 3.0) * math.pi * max_r ** 3
        vol_max = sphere_vols + cyl_vols

        print(f"  Volume: {vol:.1f} mm³  "
              f"(expected {vol_min:.0f}–{vol_max:.0f} mm³)")

        if vol < 0:
            fatal.append(f"NEGATIVE_VOLUME: {vol:.1f} mm³ — face normals inverted "
                         f"(solid is inside-out; this causes missing-chunk artefacts "
                         f"in slicers)")
        elif vol < vol_min * 0.5:
            fatal.append(f"VOLUME_TOO_SMALL: {vol:.1f} mm³ is below 50 % of "
                         f"single-sphere minimum {vol_min:.0f} mm³ — significant "
                         f"geometry is missing")
        elif vol < vol_min:
            warns.append(f"VOLUME_BELOW_MIN: {vol:.1f} mm³ is smaller than the "
                         f"largest single sphere ({vol_min:.0f} mm³); "
                         f"the fused solid may be missing primitives")
        elif vol > vol_max * 1.05:
            warns.append(f"VOLUME_TOO_LARGE: {vol:.1f} mm³ exceeds 105 % of "
                         f"no-overlap maximum {vol_max:.0f} mm³")
    except Exception as exc:
        warns.append(f"VOLUME_CHECK_ERROR: {exc}")

    # ── Checks 6, 7, 7b: point-in-solid ──────────────────────────────────
    # These checks run regardless of volume sign.  When the solid has inverted
    # normals (negative volume) BRepClass3d_SolidClassifier returns IN where
    # the correct answer is OUT and vice versa — we flip the logic in that case.
    # Verifying per-atom and per-bond presence is the primary diagnostic; total
    # volume is secondary and checked separately.
    vol_inverted = (vol is not None and vol < 0)

    def _inside(state):
        """True if the classifier state means 'inside the physical solid'."""
        if vol_inverted:
            return state == TopAbs_OUT   # normals flipped: OUT = really inside
        return state in (TopAbs_IN, TopAbs_ON)

    def _outside(state):
        if vol_inverted:
            return state in (TopAbs_IN, TopAbs_ON)
        return state == TopAbs_OUT

    try:
        clf = BRepClass3d_SolidClassifier()
        clf.Load(solid_shape)

        SAMPLE_FRAC = 0.95    # sample just inside the sphere surface
        missing_centers = []
        shaved_atoms    = []

        print()
        if vol_inverted:
            print(f"  NOTE: volume is negative — classifier in/out sense is "
                  f"flipped for checks 6, 7, 7b")

        # ── Check 6: every atom center inside the solid ────────────────────
        for atom in mol.atoms:
            pos_mm = atom.pos * scale
            r      = _atom_r(atom.vdw_radius, scale, vdw_scale, t_r)

            clf.Perform(gp_Pnt(float(pos_mm[0]),
                               float(pos_mm[1]),
                               float(pos_mm[2])), 1e-3)
            if not _inside(clf.State()):
                missing_centers.append((atom.index, atom.element,
                                        pos_mm.tolist()))
                continue   # no point sphere-checking if center is already outside

            # ── Check 7: sphere surface sampling ──────────────────────────
            bad_dirs = 0
            for dx, dy, dz in _SPHERE_SAMPLE_DIRS:
                norm = math.sqrt(dx * dx + dy * dy + dz * dz)
                clf.Perform(
                    gp_Pnt(float(pos_mm[0] + dx / norm * r * SAMPLE_FRAC),
                           float(pos_mm[1] + dy / norm * r * SAMPLE_FRAC),
                           float(pos_mm[2] + dz / norm * r * SAMPLE_FRAC)),
                    1e-3)
                if _outside(clf.State()):
                    bad_dirs += 1

            if bad_dirs > 0:
                shaved_atoms.append((atom.index, atom.element,
                                     bad_dirs, len(_SPHERE_SAMPLE_DIRS)))

        print(f"  CHECK 6 — ATOM CENTERS ({len(mol.atoms)} atoms):")
        if missing_centers:
            for idx, elem, pos in missing_centers:
                fatal.append(
                    f"ATOM_OUTSIDE: {elem}{idx} center "
                    f"({pos[0]:.2f}, {pos[1]:.2f}, {pos[2]:.2f}) mm "
                    f"is not inside the solid")
            print(f"    FAIL: {len(missing_centers)} atom center(s) outside solid")
            for idx, elem, pos in missing_centers:
                print(f"      {elem}{idx} @ ({pos[0]:.2f}, {pos[1]:.2f}, "
                      f"{pos[2]:.2f}) mm")
        else:
            print(f"    All {len(mol.atoms)} atom centers inside solid (ok)")

        print()
        print(f"  CHECK 7 — SPHERE SURFACES "
              f"({len(mol.atoms)} atoms × {len(_SPHERE_SAMPLE_DIRS)} directions):")
        if shaved_atoms:
            for idx, elem, bad, total in shaved_atoms:
                fatal.append(
                    f"SPHERE_SHAVED: {elem}{idx} — "
                    f"{bad}/{total} surface samples are outside the solid "
                    f"(sphere was truncated by boolean)")
            print(f"    FAIL: {len(shaved_atoms)} sphere(s) have missing regions")
            for idx, elem, bad, total in shaved_atoms:
                print(f"      {elem}{idx}: {bad}/{total} directions outside solid")
        else:
            print(f"    All {len(mol.atoms)} spheres intact (ok)")

        # ── Check 7b: bond cylinder midpoints inside solid ─────────────────
        missing_bonds = []
        for bond in mol.bonds:
            a1 = mol.atoms[bond.atom1_idx]
            a2 = mol.atoms[bond.atom2_idx]
            mid_mm = (a1.pos + a2.pos) * 0.5 * scale
            clf.Perform(gp_Pnt(float(mid_mm[0]),
                               float(mid_mm[1]),
                               float(mid_mm[2])), 1e-3)
            if not _inside(clf.State()):
                missing_bonds.append(
                    (bond.atom1_idx, bond.atom2_idx,
                     a1.element, a2.element, mid_mm.tolist()))

        print()
        print(f"  CHECK 7b — BOND MIDPOINTS ({len(mol.bonds)} bonds):")
        if missing_bonds:
            for i1, i2, e1, e2, pos in missing_bonds:
                fatal.append(
                    f"BOND_OUTSIDE: {e1}{i1}-{e2}{i2} midpoint "
                    f"({pos[0]:.2f}, {pos[1]:.2f}, {pos[2]:.2f}) mm "
                    f"is not inside the solid — cylinder may be missing")
            print(f"    FAIL: {len(missing_bonds)} bond midpoint(s) outside solid")
            for i1, i2, e1, e2, pos in missing_bonds:
                print(f"      {e1}{i1}-{e2}{i2} @ "
                      f"({pos[0]:.2f}, {pos[1]:.2f}, {pos[2]:.2f}) mm")
        else:
            print(f"    All {len(mol.bonds)} bond midpoints inside solid (ok)")

    except Exception as exc:
        warns.append(f"POINT_IN_SOLID_ERROR: {exc}")

    # ── Check 8: bounding box ─────────────────────────────────────────────
    try:
        bbox = Bnd_Box()
        BRepBndLib.Add_s(solid_shape, bbox)
        xmin, ymin, zmin, xmax, ymax, zmax = bbox.Get()

        exp_xmin = exp_ymin = exp_zmin =  float("inf")
        exp_xmax = exp_ymax = exp_zmax = -float("inf")
        for atom in mol.atoms:
            r   = _atom_r(atom.vdw_radius, scale, vdw_scale, t_r)
            pos = atom.pos * scale
            exp_xmin = min(exp_xmin, pos[0] - r)
            exp_ymin = min(exp_ymin, pos[1] - r)
            exp_zmin = min(exp_zmin, pos[2] - r)
            exp_xmax = max(exp_xmax, pos[0] + r)
            exp_ymax = max(exp_ymax, pos[1] + r)
            exp_zmax = max(exp_zmax, pos[2] + r)

        tol_bb = max(t_r * 0.5, 0.5)
        bb_issues = []
        for axis, act_lo, act_hi, exp_lo, exp_hi in [
            ("X", xmin, xmax, exp_xmin, exp_xmax),
            ("Y", ymin, ymax, exp_ymin, exp_ymax),
            ("Z", zmin, zmax, exp_zmin, exp_zmax),
        ]:
            shrink_lo = act_lo - exp_lo   # positive → actual is larger than expected (interior shrinkage at low end)
            shrink_hi = exp_hi - act_hi   # positive → actual is smaller than expected (interior shrinkage at high end)
            if shrink_lo > tol_bb:
                bb_issues.append(f"{axis} low: actual {act_lo:.2f} > expected {exp_lo:.2f} "
                                 f"(solid shrunk {shrink_lo:.2f} mm on -{axis} side)")
            if shrink_hi > tol_bb:
                bb_issues.append(f"{axis} high: actual {act_hi:.2f} < expected {exp_hi:.2f} "
                                 f"(solid shrunk {shrink_hi:.2f} mm on +{axis} side)")

        print()
        print(f"  CHECK 8 — BOUNDING BOX:")
        if bb_issues:
            for issue in bb_issues:
                warns.append(f"BBOX_SHRINK: {issue}")
            print(f"    {len(bb_issues)} extent(s) smaller than expected:")
            for issue in bb_issues:
                print(f"      {issue}")
        else:
            ext = (xmax - xmin, ymax - ymin, zmax - zmin)
            print(f"    {ext[0]:.1f} × {ext[1]:.1f} × {ext[2]:.1f} mm — "
                  f"matches expected envelope (ok)")

    except Exception as exc:
        warns.append(f"BBOX_CHECK_ERROR: {exc}")

    # ── Summary ───────────────────────────────────────────────────────────
    print()
    if fatal:
        print(f"  FATAL ({len(fatal)}):")
        for f in fatal:
            print(f"    ✗ {f}")
    if warns:
        print(f"  WARNINGS ({len(warns)}):")
        for w in warns:
            print(f"    ! {w}")

    if not fatal and not warns:
        print("  RESULT: PASS — single fused solid, all spheres intact, "
              "geometry valid")
    elif not fatal:
        print(f"  RESULT: PASS with {len(warns)} warning(s)")
    else:
        print(f"  RESULT: FAIL — {len(fatal)} fatal issue(s)")
    print("=" * 70)
    return len(fatal) == 0


def check_solid_integrity(step_file, check_intersections=False):
    """
    Check BREP integrity of every solid in a STEP file using OCCT validators.

    Three checks are run per solid:
      1. BRepCheck_Analyzer          — topology & geometry validity (37 error codes)
      2. ShapeAnalysis_ShapeContents — free edges / faces (watertightness proxy)
      3. BRepGProp.VolumeProperties  — volume sign (negative = inverted orientation)

    Optional (slow, off by default):
      4. BRepAlgoAPI_Check           — self-intersection detection

    Issues are classified as:
      FATAL — would typically cause slicing to fail or produce broken prints
      WARN  — may cause problems depending on slicer tolerance

    Returns True if no fatal issues were found.
    """
    import cadquery as cq
    from OCP.BRepCheck import BRepCheck_Analyzer, BRepCheck_Status
    from OCP.ShapeAnalysis import ShapeAnalysis_ShapeContents
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_SHELL, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX

    # ── Classification tables (string-keyed for robustness across OCP versions) ──
    _FATAL_NAMES = {
        "BRepCheck_NotClosed",
        "BRepCheck_NotConnected",
        "BRepCheck_FreeEdge",
        "BRepCheck_SelfIntersectingWire",
        "BRepCheck_IntersectingWires",
        "BRepCheck_BadOrientation",
        "BRepCheck_BadOrientationOfSubshape",
        "BRepCheck_UnorientableShape",
        "BRepCheck_EmptyShell",
        "BRepCheck_EmptyWire",
        "BRepCheck_InvalidImbricationOfShells",
    }

    _DESC = {
        "BRepCheck_NotClosed":
            "shell not closed (open / not watertight)",
        "BRepCheck_NotConnected":
            "disconnected shell",
        "BRepCheck_FreeEdge":
            "free edge — belongs to only one face (non-manifold)",
        "BRepCheck_SelfIntersectingWire":
            "self-intersecting wire",
        "BRepCheck_IntersectingWires":
            "intersecting wires",
        "BRepCheck_BadOrientation":
            "bad face orientation (inverted normal)",
        "BRepCheck_BadOrientationOfSubshape":
            "bad sub-shape orientation",
        "BRepCheck_UnorientableShape":
            "unorientable shape",
        "BRepCheck_EmptyShell":
            "empty shell (no faces)",
        "BRepCheck_EmptyWire":
            "empty wire (no edges)",
        "BRepCheck_InvalidSameParameterFlag":
            "invalid same-parameter flag",
        "BRepCheck_InvalidSameRangeFlag":
            "invalid same-range flag",
        "BRepCheck_InvalidPointOnSurface":
            "invalid point on surface",
        "BRepCheck_InvalidPointOnCurve":
            "invalid point on curve",
        "BRepCheck_InvalidCurveOnSurface":
            "invalid curve on surface",
        "BRepCheck_CheckFail":
            "OCCT shape-check failed (internal error)",
        "BRepCheck_InvalidWire":
            "invalid wire",
        "BRepCheck_InvalidRange":
            "invalid parameter range",
        "BRepCheck_InvalidToleranceValue":
            "invalid tolerance value",
        "BRepCheck_RedundantEdge":
            "redundant edge",
        "BRepCheck_RedundantFace":
            "redundant face",
        "BRepCheck_InvalidImbricationOfShells":
            "invalid shell nesting",
        "BRepCheck_SubshapeNotInShape":
            "sub-shape not in parent shape",
    }

    def _status_name(s):
        """Extract 'BRepCheck_XxxYyy' string from an OCP enum value.

        OCP 7.8 formats the enum as 'BRepCheck_Status.BRepCheck_NotClosed'
        (no angle brackets); older or debug builds may include '<...>'.
        We take the last dot-separated component in all cases.
        """
        raw = str(s).strip("<>").split(":")[0].strip()
        return raw.split(".")[-1]

    def _collect_status_names(result):
        """Iterate a BRepCheck_ListOfStatus, return set of status name strings."""
        names = set()
        sl = result.Status()
        try:
            for s in sl:                    # OCP wraps most NCollection_List as iterable
                names.add(_status_name(s))
        except TypeError:
            # Fallback: 1-based Value() access
            for i in range(sl.Extent()):
                try:
                    names.add(_status_name(sl.Value(i + 1)))
                except Exception:
                    pass
        return names

    # ── Load file ─────────────────────────────────────────────────────────────
    print("=" * 70)
    print(f"SOLID INTEGRITY CHECK  ({step_file})")
    print("=" * 70)

    from OCP.TopAbs import TopAbs_SOLID, TopAbs_SHELL, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX

    occ_shape, load_err = _load_step_occ(step_file)
    if occ_shape is None:
        print(f"  ERROR: Cannot load STEP file: {load_err}")
        return False

    # Use TopExp_Explorer for reliable traversal (CadQuery's .solids() returns
    # 0 solids for fused output due to shape-tree traversal differences)
    solids_raw = _topo_explore(occ_shape, TopAbs_SOLID)
    # Wrap as cq.Shape for the per-solid checks below
    import cadquery as cq
    solids = [cq.Shape.cast(s) for s in solids_raw]
    n_solids = len(solids)
    print(f"  Solids: {n_solids}")
    if n_solids == 0:
        print("  ERROR: No solids found in file.")
        return False
    print()

    global_fatal = 0
    global_warn  = 0
    global_ok    = 0
    # For large compounds, suppress OK-solid lines to avoid noise
    compact = n_solids > 20

    for idx, solid in enumerate(solids, 1):
        fatals = []   # (label, description) — would break slicing
        warns  = []   # (label, description) — slicer-dependent

        # ── Check 1: BRepCheck_Analyzer ───────────────────────────────
        try:
            ana = BRepCheck_Analyzer(solid.wrapped, True)
            if not ana.IsValid():
                seen = set()
                for sub_type in (TopAbs_SHELL, TopAbs_FACE,
                                  TopAbs_EDGE, TopAbs_VERTEX):
                    exp = TopExp_Explorer(solid.wrapped, sub_type)
                    while exp.More():
                        sub = exp.Current()
                        try:
                            seen |= _collect_status_names(ana.Result(sub))
                        except Exception:
                            pass
                        exp.Next()

                for name in seen:
                    if name == "BRepCheck_NoError":
                        continue
                    desc = _DESC.get(name, name)
                    if name in _FATAL_NAMES:
                        fatals.append((name, desc))
                    else:
                        warns.append((name, desc))
        except Exception as exc:
            warns.append(("BRepCheck_Analyzer", f"check raised: {exc}"))

        # ── Check 2: ShapeAnalysis_ShapeContents ──────────────────────
        n_shells = n_faces = free_edges = free_faces = 0
        try:
            contents = ShapeAnalysis_ShapeContents()
            contents.Perform(solid.wrapped)
            n_shells   = contents.NbShells()
            n_faces    = contents.NbFaces()
            free_edges = contents.NbFreeEdges()
            free_faces = contents.NbFreeFaces()
            if free_edges > 0:
                fatals.append(("FreeEdges",
                    f"{free_edges} free edge(s) — non-manifold / open shell"))
            if free_faces > 0:
                fatals.append(("FreeFaces",
                    f"{free_faces} free face(s) — disconnected geometry"))
        except Exception as exc:
            warns.append(("ShapeAnalysis", f"check raised: {exc}"))

        # ── Check 3: Volume sign ──────────────────────────────────────
        vol_str = "?"
        try:
            props = GProp_GProps()
            BRepGProp.VolumeProperties_s(solid.wrapped, props)
            vol = props.Mass()
            vol_str = f"{vol:.1f} mm³"
            if vol < 0:
                fatals.append(("NegativeVolume",
                    f"volume = {vol:.2f} mm³ — faces oriented inward"))
            elif vol == 0:
                fatals.append(("ZeroVolume", "zero volume — degenerate solid"))
        except Exception as exc:
            warns.append(("Volume", f"check raised: {exc}"))

        # ── Check 4: Self-intersection (optional) ─────────────────────
        if check_intersections:
            try:
                from OCP.BRepAlgoAPI import BRepAlgoAPI_Check
                chk = BRepAlgoAPI_Check(solid.wrapped, False, True)
                chk.Perform()
                if not chk.IsValid():
                    fatals.append(("SelfIntersection",
                        "solid self-intersects (BRepAlgoAPI_Check)"))
            except Exception as exc:
                warns.append(("SelfIntersection", f"check raised: {exc}"))

        # ── Per-solid report ──────────────────────────────────────────
        tag = "FAIL" if fatals else ("WARN" if warns else "OK  ")
        if fatals or warns:
            print(f"  [{tag}] solid {idx:3d}/{n_solids}"
                  f"  vol={vol_str}  shells={n_shells}  faces={n_faces}")
            for lbl, desc in sorted(set(fatals)):
                print(f"           FATAL  {lbl}: {desc}")
            for lbl, desc in sorted(set(warns)):
                print(f"           WARN   {lbl}: {desc}")
        elif not compact:
            print(f"  [{tag}] solid {idx:3d}/{n_solids}"
                  f"  vol={vol_str}  shells={n_shells}  faces={n_faces}")
        else:
            global_ok += 1

        global_fatal += len(fatals)
        global_warn  += len(warns)

    # ── Summary ───────────────────────────────────────────────────────
    if global_ok:
        print(f"  [OK  ] ({global_ok} solid(s) with no issues — omitted)")
    print()
    if global_fatal:
        print(f"  RESULT: {global_fatal} fatal issue(s), {global_warn} warning(s)"
              f" across {n_solids} solid(s).")
        print("  Slicing is likely to fail.  Recommended actions:")
        print("    • Re-run with --union to fuse all hubs into one manifold solid.")
        print("    • Open in FreeCAD → Part → Check Geometry for an interactive report.")
        print("    • Use MeshMixer or Netfabb repair on the STL export.")
    elif global_warn:
        print(f"  RESULT: 0 fatal, {global_warn} warning(s).  "
              "File may import with slicer warnings.")
    else:
        print(f"  RESULT: All {n_solids} solid(s) passed.  "
              "File should slice cleanly.")
    print("=" * 70)
    return global_fatal == 0


def export_model(shape, filepath, fmt="step", skip_normalize=False):
    """Export a CadQuery Shape/Compound/Assembly to STEP or STL."""
    import cadquery as cq
    is_assembly = isinstance(shape, cq.Assembly)
    if fmt in ("step", "stp"):
        if is_assembly:
            shape.save(filepath, exportType="STEP")
        else:
            from OCP.STEPControl import STEPControl_Writer, STEPControl_AsIs
            from OCP.Interface import Interface_Static
            from OCP.IFSelect import IFSelect_RetDone
            # Resolve accumulated compound-context orientation flags before
            # export: the STEP translator cannot handle the multi-level context
            # produced by sequential pairwise fuse and mis-orients faces.
            if skip_normalize:
                print("  [--skip-normalize] bypassing _normalize_shell_orientations")
                normalized = shape
            else:
                normalized = _normalize_shell_orientations(shape)
            _diag_orientation(normalized, "after_normalize")
            writer = STEPControl_Writer()
            Interface_Static.SetCVal_s("write.step.schema", "AP203")
            writer.Transfer(normalized.wrapped, STEPControl_AsIs)
            status = writer.Write(str(filepath))
            if status != IFSelect_RetDone:
                raise RuntimeError(f"STEP export failed (status {status})")
            # Diagnostic B: what orientation flags did the writer put in the file?
            try:
                with open(filepath) as _f:
                    _lines = _f.readlines()
                for _l in _lines:
                    if "MANIFOLD_SOLID_BREP" in _l or "CLOSED_SHELL" in _l:
                        print(f"  DIAG [STEP file] {_l.rstrip()}")
                _af = [_l.rstrip() for _l in _lines if "ADVANCED_FACE" in _l]
                print(f"  DIAG [STEP file] {len(_af)} ADVANCED_FACE entries; "
                      f"same_sense flags: "
                      f"{sum(1 for l in _af if l.rstrip().endswith('.T.);'))} .T. / "
                      f"{sum(1 for l in _af if l.rstrip().endswith('.F.);'))} .F.")
                for _l in _af[:3]:
                    print(f"  DIAG [STEP file]   {_l}")
            except Exception as _e:
                print(f"  DIAG [STEP file] could not read: {_e}")
    elif fmt == "stl":
        src = shape.toCompound() if is_assembly else shape
        cq.exporters.export(src, filepath, exportType="STL",
                            tolerance=0.01, angularTolerance=0.1)
    else:
        raise ValueError(f"Unsupported format: {fmt}")


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(
        prog="mol2step.py",
        description=(
            "Generate solid BREP CAD files (STEP or STL) of ball-and-stick\n"
            "molecular models from molecular geometry files.\n\n"
            "Architecture: all sphere and cylinder primitives fused in one\n"
            "BRepAlgoAPI_Fuse call (multi-tool mode) to produce a single\n"
            "BREP solid.  Use --no-fillet for a compound of overlapping\n"
            "primitives (no boolean, always valid STEP)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=r"""
SCALE CONVENTION
  All distances are in mm.  Angstrom positions are multiplied by --scale.

  Atom sphere diameter  =  VdW_radius(A) * --vdw-scale * --scale
                        =  1 A  ->  1 cm diameter  (at defaults)

  Bond tube diameter    =  VdW_H(1.2 A) * --bond-scale * --scale
                        =  defaults give 8.4 mm diameter (bond-scale 0.7)

JUNCTION GEOMETRY
  At each sphere-tube junction the key metrics are:
    overlap  = sphere_radius - tube_radius  (tube embedded this far in sphere)
    angle    = arcsin(sqrt(r^2 - t^2) / r)  (surface meeting angle; 90=ideal)
  Both are printed at build time.  overlap < 0.3 mm or angle < 10 deg will
  produce visible seam artefacts.  Use --check-step to inspect after building.

INPUT FORMATS
  .mol / .sdf   MDL Molfile — explicit bond table, best choice
  .xyz          XYZ coordinates — bonds inferred from covalent radii + tolerance
  .pdb          PDB — CONECT records used; falls back to distance inference
  .cjson        Chemical JSON (Avogadro2 native format)

OUTPUT
  Default: <input_stem>.step  (STEP AP214, true BREP solid geometry)
  With --format stl: triangulated mesh for direct slicing

WORKFLOW
  1.  Obtain geometry:
        Avogadro2  ->  File > Export > Molecule (.cjson or .mol)
        PubChem    ->  Download > SDF (rename .sdf -> .mol, or use as-is)
        OpenBabel  ->  obabel input.pdb -O output.mol --gen3d

  2.  Generate STEP:
        python mol2step.py molecule.cjson -o molecule.step

  3.  Check for gaps (optional):
        python mol2step.py molecule.cjson --check-step molecule.step

  4.  Open in FreeCAD or OnShape:
        Inspect solid, add support struts or base plate as needed

  5.  Export STL / 3MF and slice in PrusaSlicer

EXAMPLES
  # Basic — defaults (vdw-scale 1.0, bond-scale 0.7)
  python mol2step.py caffeine.cjson -o caffeine.step

  # Smaller atoms and thinner bonds (good for larger molecules)
  python mol2step.py molecule.cjson --vdw-scale 0.7 --bond-scale 0.5

  # Print sizing table without building
  python mol2step.py molecule.cjson --info

  # Check junction geometry of an existing STEP file
  python mol2step.py molecule.cjson --check-step molecule.step

  # Add a base plate for bed adhesion
  python mol2step.py molecule.cjson --add-base --base-thickness 3.0

  # STL output (for direct slicing without CAD step)
  python mol2step.py molecule.cjson -o molecule.stl --format stl

  # Verbose bond/geometry validation
  python mol2step.py molecule.cjson --debug --info

PARAMETER GUIDE FOR 3D PRINTING
  Parameter        Default   Notes
  ───────────────────────────────────────────────────────────────────
  --scale          10.0      mm per Angstrom; increase for larger print
  --vdw-scale      1.0       atom sphere size multiplier
  --bond-scale     0.7       bond tube size multiplier (0.5-0.7 recommended)
  --bond-tolerance 0.4       Angstrom tolerance for bond inference (XYZ/PDB)

  Rule of thumb: bond-scale 0.5-0.7 keeps tubes noticeably thinner than atom
  spheres, which eliminates near-tangent junction artefacts.  The junction
  overlap and angle are printed at build time — look for "ok" on all elements.
""")

    # Positional — optional when --check-integrity is the only goal
    p.add_argument("input", nargs="?", default=None,
                   help="Molecule file (.mol .sdf .xyz .pdb .cjson); "
                        "not required when using --check-integrity alone")

    # Output
    p.add_argument("-o", "--output",
                   help="Output file path (default: <input_stem>.step or .stl)")
    p.add_argument("-f", "--format", choices=["step", "stp", "stl"],
                   default="step",
                   help="Output format: step (default), stp, or stl")

    # Scale
    p.add_argument("--scale", type=float, default=10.0,
                   help="Position scale in mm/Angstrom (default: 10.0)")
    p.add_argument("--vdw-scale", type=float, default=1.0,
                   help="Atom sphere radius multiplier (default: 1.0)")
    p.add_argument("--bond-scale", type=float, default=0.7,
                   help="Bond tube radius multiplier (default: 0.7; "
                        "keeps tubes thinner than H spheres to avoid gaps)")

    # Geometry overrides
    p.add_argument("--tube-radius", type=float, default=None,
                   help="Hard-override tube radius in mm (overrides --bond-scale)")
    p.add_argument("--no-fillet", action="store_true",
                   help="Export raw overlapping sphere+cylinder compound "
                        "(no boolean union)")
    p.add_argument("--skip-normalize", action="store_true",
                   help="Skip _normalize_shell_orientations before STEP export "
                        "(diagnostic: test whether normalization is the source of "
                        "orientation errors)")
    p.add_argument("--union", action="store_true",
                   help="Accepted for backward compatibility; has no effect "
                        "(the default path always produces a single fused solid)")
    p.add_argument("--bond-tolerance", type=float, default=0.4,
                   help="Bond-inference distance tolerance in Angstroms "
                        "for XYZ/PDB files (default: 0.4)")
    p.add_argument("--min-bond-dist", type=float, default=MIN_BOND_DIST,
                   help=f"Minimum interatomic distance (Å) treated as a bond "
                        f"during inference (default: {MIN_BOND_DIST})")

    # Base plate
    p.add_argument("--add-base", action="store_true",
                   help="Add a rectangular base plate for bed adhesion")
    p.add_argument("--base-thickness", type=float, default=3.0,
                   help="Base plate thickness in mm (default: 3.0)")
    p.add_argument("--base-margin", type=float, default=5.0,
                   help="Base plate margin beyond molecule extent in mm "
                        "(default: 5.0)")

    # Misc
    p.add_argument("--no-center", action="store_true",
                   help="Do not translate molecule to origin before building")
    p.add_argument("--info", action="store_true",
                   help="Print atom/tube sizing table and exit (no build)")
    p.add_argument("--debug", action="store_true",
                   help="Run verbose geometry validation (bond lengths, "
                        "sphere/tube clearances) and print report")

    # Gap check
    p.add_argument("--check-step", metavar="STEP_FILE",
                   help="Analyse junction geometry (overlap and angle) for "
                        "every bond endpoint in STEP_FILE and report; "
                        "also verifies body count.  No build needed.")
    p.add_argument("--check-integrity", metavar="STEP_FILE",
                   help="Run OCCT BREP integrity checks on STEP_FILE: topology "
                        "validity (BRepCheck_Analyzer), free edges/faces "
                        "(ShapeAnalysis), and volume sign.  Reports FATAL / WARN "
                        "issues per solid.  No build needed.")
    p.add_argument("--check-self-intersect", action="store_true",
                   help="Add self-intersection test to --check-integrity "
                        "(slow: O(n²) in face count; use on small files only)")
    args = p.parse_args()

    # --check-integrity doesn't need a molecule file
    if args.check_integrity and args.input is None:
        check_solid_integrity(args.check_integrity,
                              check_intersections=args.check_self_intersect)
        return

    if args.input is None:
        p.error("input file is required unless --check-integrity is used alone")

    print(f"Loading: {args.input}")
    mol = load_molecule(args.input, args.bond_tolerance, args.min_bond_dist)
    if validate_molecule(mol) > 0:
        print("  (warnings above may cause geometry errors — review input file)")
    if not args.no_center:
        mol.center_on_origin()

    t_r = tube_radius_mm(args.scale, args.bond_scale, args.tube_radius)

    bb_min, bb_max = mol.bounding_box()
    ext = (bb_max - bb_min) * args.scale

    print(f"  Name: {mol.name}")
    print(f"  Atoms: {len(mol.atoms)}  Bonds: {len(mol.bonds)}")
    print(f"  VdW scale: {args.vdw_scale}x  Bond scale: {args.bond_scale}x")

    elems = sorted(set(a.element for a in mol.atoms))
    print(f"\n  {'Elem':4s}  {'VdW(A)':>6s}  {'r(mm)':>7s}  {'d(mm)':>7s}")
    print(f"  {'----':4s}  {'------':>6s}  {'-----':>7s}  {'-----':>7s}")
    for e in elems:
        vdw = VDW_RADII.get(e, DEFAULT_VDW_RADIUS)
        r = _atom_r(vdw, args.scale, args.vdw_scale, t_r)
        print(f"  {e:4s}  {vdw:6.2f}  {r:7.2f}  {r*2:7.2f}")
    print(f"  {'tube':4s}  {VDW_RADII['H']:6.2f}  {t_r:7.2f}  {t_r*2:7.2f}")
    print(f"\n  Bounding box: {bb_min.round(2)} to {bb_max.round(2)} A")
    print(f"  Model extent: {ext[0]:.1f} x {ext[1]:.1f} x {ext[2]:.1f} mm")

    if args.check_step:
        check_step_gaps(args.check_step, mol,
                        args.scale, args.vdw_scale, args.bond_scale,
                        args.tube_radius)
        return

    if args.check_integrity:
        check_solid_integrity(args.check_integrity,
                              check_intersections=args.check_self_intersect)
        return

    if args.debug:
        validate_geometry(mol, args.scale, args.vdw_scale, args.bond_scale,
                          args.tube_radius)

    if args.info:
        return

    if not mol.bonds:
        print("\nERROR: No bonds found.  For XYZ/PDB files try "
              "--bond-tolerance 0.5")
        sys.exit(1)

    if args.output is None:
        stem = Path(args.input).stem
        args.output = f"{stem}.{'stl' if args.format == 'stl' else 'step'}"

    print(f"\nBuilding model...")
    shape = build_model(
        mol, args.scale, args.vdw_scale, args.bond_scale,
        args.tube_radius, args.no_fillet,
        args.add_base, args.base_thickness, args.base_margin)

    print(f"  Exporting: {args.output}")
    export_model(shape, args.output, args.format,
                 skip_normalize=args.skip_normalize)
    print(f"Done -> {args.output}")

    if args.no_fillet:
        n_bodies = len(shape.Solids())
        print(f"\n  Compound: {n_bodies} separate bodies "
              f"(--no-fillet mode — no boolean union).")
    elif args.format in ("step", "stp"):
        print()
        check_final_output(args.output, mol,
                           args.scale, args.vdw_scale, args.bond_scale,
                           args.tube_radius)


if __name__ == "__main__":
    main()
