#!/usr/bin/env python3
"""
mol2step.py — Generate solid STEP/STL CAD files of ball-and-stick molecular
models from molecular geometry files (MOL/SDF, XYZ, PDB).

Atom spheres are sized by van der Waals radius. Bond tubes are sized by
the van der Waals radius of hydrogen. Sphere–tube intersections are
automatically filleted for printability.

Produces true solid BREP geometry that imports into OnShape, FreeCAD, or
any STEP-compatible CAD program.

Requirements:
    conda/mamba install -c conda-forge cadquery numpy

Usage:
    python mol2step.py molecule.mol -o molecule.step
    python mol2step.py molecule.mol --vdw-scale 0.5 --bond-scale 0.3
    python mol2step.py molecule.mol --debug   # verbose geometry validation

Scale convention (default --scale 10):
    1 Å VdW radius  →  1 cm sphere diameter
    Bond tubes sized to H VdW × bond-scale

Author: Generated by Claude for foton's molecular printing workflow
License: AGPL-3.0-or-later
"""

import argparse
import json
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np

# ═══════════════════════════════════════════════════════════════════════════
# DATA TABLES
# ═══════════════════════════════════════════════════════════════════════════

# Van der Waals radii (Å) — 96 elements, Z=1..96
# Mantina et al., J. Phys. Chem. A 2009, 113, 5806 (main group)
# Alvarez, Dalton Trans. 2013, 42, 8617 (d-block, f-block)
# Bondi, J. Phys. Chem. 1964, 68, 441 (original)
VDW_RADII = {
    "H":  1.20, "He": 1.40,
    "Li": 1.81, "Be": 1.53, "B":  1.92, "C":  1.70, "N":  1.55,
    "O":  1.52, "F":  1.47, "Ne": 1.54,
    "Na": 2.27, "Mg": 1.73, "Al": 1.84, "Si": 2.10, "P":  1.80,
    "S":  1.80, "Cl": 1.75, "Ar": 1.88,
    "K":  2.75, "Ca": 2.31,
    "Sc": 2.15, "Ti": 2.11, "V":  2.07, "Cr": 2.06, "Mn": 2.05,
    "Fe": 2.04, "Co": 2.00, "Ni": 1.97, "Cu": 1.96, "Zn": 2.01,
    "Ga": 1.87, "Ge": 2.11, "As": 1.85, "Se": 1.90, "Br": 1.83,
    "Kr": 2.02,
    "Rb": 3.03, "Sr": 2.49,
    "Y":  2.32, "Zr": 2.23, "Nb": 2.18, "Mo": 2.17, "Tc": 2.16,
    "Ru": 2.13, "Rh": 2.10, "Pd": 2.10, "Ag": 2.11, "Cd": 2.18,
    "In": 1.93, "Sn": 2.17, "Sb": 2.06, "Te": 2.06, "I":  1.98,
    "Xe": 2.16,
    "Cs": 3.43, "Ba": 2.68,
    "La": 2.43, "Ce": 2.42, "Pr": 2.40, "Nd": 2.39, "Pm": 2.38,
    "Sm": 2.36, "Eu": 2.35, "Gd": 2.34, "Tb": 2.33, "Dy": 2.31,
    "Ho": 2.30, "Er": 2.29, "Tm": 2.27, "Yb": 2.26, "Lu": 2.24,
    "Hf": 2.23, "Ta": 2.22, "W":  2.18, "Re": 2.16, "Os": 2.16,
    "Ir": 2.13, "Pt": 2.13, "Au": 2.14, "Hg": 2.23,
    "Tl": 1.96, "Pb": 2.02, "Bi": 2.07, "Po": 1.97, "At": 2.02,
    "Rn": 2.20,
    "Fr": 3.48, "Ra": 2.83,
    "Ac": 2.47, "Th": 2.45, "Pa": 2.43, "U":  2.41, "Np": 2.39,
    "Pu": 2.43, "Am": 2.44, "Cm": 2.45,
}
DEFAULT_VDW_RADIUS = 2.00

# Covalent radii (Å) for bond inference — Cordero et al., Dalton Trans. 2008
COVALENT_RADII = {
    "H":  0.31, "He": 0.28,
    "Li": 1.28, "Be": 0.96, "B":  0.84, "C":  0.76, "N":  0.71,
    "O":  0.66, "F":  0.57, "Ne": 0.58,
    "Na": 1.66, "Mg": 1.41, "Al": 1.21, "Si": 1.11, "P":  1.07,
    "S":  1.05, "Cl": 1.02, "Ar": 1.06,
    "K":  2.03, "Ca": 1.76,
    "Sc": 1.70, "Ti": 1.60, "V":  1.53, "Cr": 1.39, "Mn": 1.39,
    "Fe": 1.32, "Co": 1.26, "Ni": 1.24, "Cu": 1.32, "Zn": 1.22,
    "Ga": 1.22, "Ge": 1.20, "As": 1.19, "Se": 1.20, "Br": 1.20,
    "Kr": 1.16,
    "Rb": 2.20, "Sr": 1.95,
    "Y":  1.90, "Zr": 1.75, "Nb": 1.64, "Mo": 1.54, "Tc": 1.47,
    "Ru": 1.46, "Rh": 1.42, "Pd": 1.39, "Ag": 1.45, "Cd": 1.44,
    "In": 1.42, "Sn": 1.39, "Sb": 1.39, "Te": 1.38, "I":  1.39,
    "Xe": 1.40,
    "Cs": 2.44, "Ba": 2.15,
    "La": 2.07, "Ce": 2.04, "Pr": 2.03, "Nd": 2.01, "Pm": 1.99,
    "Sm": 1.98, "Eu": 1.98, "Gd": 1.96, "Tb": 1.94, "Dy": 1.92,
    "Ho": 1.92, "Er": 1.89, "Tm": 1.90, "Yb": 1.87, "Lu": 1.87,
    "Hf": 1.75, "Ta": 1.70, "W":  1.62, "Re": 1.51, "Os": 1.44,
    "Ir": 1.41, "Pt": 1.36, "Au": 1.36, "Hg": 1.32,
    "Tl": 1.45, "Pb": 1.46, "Bi": 1.48, "Po": 1.40, "At": 1.50,
    "Rn": 1.50,
    "Fr": 2.60, "Ra": 2.21,
    "Ac": 2.15, "Th": 2.06, "Pa": 2.00, "U":  1.96, "Np": 1.90,
    "Pu": 1.87, "Am": 1.80, "Cm": 1.69,
}
DEFAULT_COVALENT_RADIUS = 1.50
MIN_BOND_DIST = 0.4  # Å — minimum interatomic distance treated as a bond


# ═══════════════════════════════════════════════════════════════════════════
# MOLECULE DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class Atom:
    index: int
    element: str
    x: float
    y: float
    z: float

    @property
    def pos(self):
        return np.array([self.x, self.y, self.z])

    @property
    def vdw_radius(self):
        return VDW_RADII.get(self.element, DEFAULT_VDW_RADIUS)

    @property
    def covalent_radius(self):
        return COVALENT_RADII.get(self.element, DEFAULT_COVALENT_RADIUS)


@dataclass
class Bond:
    atom1_idx: int
    atom2_idx: int
    order: int = 1


@dataclass
class Molecule:
    name: str = "molecule"
    atoms: list = field(default_factory=list)
    bonds: list = field(default_factory=list)

    def center_on_origin(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        com = coords.mean(axis=0)
        for a in self.atoms:
            a.x -= com[0]; a.y -= com[1]; a.z -= com[2]

    def bounding_box(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        return coords.min(axis=0), coords.max(axis=0)

    def adjacency(self):
        """Return {atom_idx: [(bond, neighbor_atom)]} for every atom."""
        adj = {a.index: [] for a in self.atoms}
        for bond in self.bonds:
            a1 = self.atoms[bond.atom1_idx]
            a2 = self.atoms[bond.atom2_idx]
            adj[bond.atom1_idx].append((bond, a2))
            adj[bond.atom2_idx].append((bond, a1))
        return adj


# ═══════════════════════════════════════════════════════════════════════════
# GEOMETRY HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def _bond_offsets(d_hat, order, t_r):
    """
    Return [(offset_vector, cylinder_radius)] for each strand of a bond.

    Single bond: one entry — zero offset, radius t_r.
    Multi bond:  `order` entries evenly distributed angularly around d_hat,
                 using reduced radius (t_r * 0.65) and lateral offset (t_r * 0.85).

    d_hat must be a unit numpy array along the bond axis.
    """
    if order == 1:
        return [(np.zeros(3), t_r)]
    mr = t_r * 0.65
    od = t_r * 0.85
    ref = np.array([0.0, 0.0, 1.0]) if abs(d_hat[2]) < 0.707 \
          else np.array([1.0, 0.0, 0.0])
    u = np.cross(d_hat, ref)
    u /= np.linalg.norm(u)
    v = np.cross(d_hat, u)
    result = []
    for k in range(order):
        theta = math.pi * k if order == 2 else 2.0 * math.pi * k / order
        off = od * (math.cos(theta) * u + math.sin(theta) * v)
        result.append((off, mr))
    return result


# ═══════════════════════════════════════════════════════════════════════════
# FILE PARSERS
# ═══════════════════════════════════════════════════════════════════════════

def parse_mol_file(filepath):
    filepath = Path(filepath)
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    if len(lines) < 4:
        raise ValueError(f"{filepath}: too short to be a valid V2000 MOL file")
    mol.name = lines[0].strip() or filepath.stem
    # V2000 counts line uses fixed-width fields: cols 0-2 = atom count, 3-5 = bond count
    counts_line = lines[3]
    try:
        na, nb = int(counts_line[0:3]), int(counts_line[3:6])
    except ValueError:
        raise ValueError(f"{filepath}: malformed counts line: {counts_line!r}")
    if len(lines) < 4 + na + nb:
        raise ValueError(
            f"{filepath}: file truncated (expected {4 + na + nb} lines, got {len(lines)})")
    # V2000 atom block: cols 0-9 = x, 10-19 = y, 20-29 = z, 31-33 = element symbol
    for i in range(na):
        ln = lines[4 + i]
        try:
            x, y, z = float(ln[0:10]), float(ln[10:20]), float(ln[20:30])
            elem = ln[31:34].strip()
        except (ValueError, IndexError):
            raise ValueError(f"{filepath}: malformed atom line {4 + i + 1}: {ln!r}")
        if not elem:
            raise ValueError(f"{filepath}: empty element symbol on atom line {4 + i + 1}")
        mol.atoms.append(Atom(i, elem, x, y, z))
    # V2000 bond block: cols 0-2 = atom1, 3-5 = atom2, 6-8 = bond order
    for i in range(nb):
        ln = lines[4 + na + i]
        try:
            a1, a2, order = int(ln[0:3]), int(ln[3:6]), int(ln[6:9])
        except (ValueError, IndexError):
            raise ValueError(f"{filepath}: malformed bond line {4 + na + i + 1}: {ln!r}")
        mol.bonds.append(Bond(a1 - 1, a2 - 1, order))
    return mol


def parse_xyz_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    na = int(lines[0].strip())
    mol.name = lines[1].strip() or Path(filepath).stem
    for i in range(na):
        p = lines[2 + i].split()
        elem = p[0][0].upper() + p[0][1:].lower() if len(p[0]) > 1 else p[0].upper()
        mol.atoms.append(Atom(i, elem, float(p[1]), float(p[2]), float(p[3])))
    for i in range(na):
        for j in range(i + 1, na):
            ai, aj = mol.atoms[i], mol.atoms[j]
            d = np.linalg.norm(ai.pos - aj.pos)
            if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                mol.bonds.append(Bond(i, j))
    return mol


def _pdb_element_from_name(name_field):
    """Derive element symbol from PDB atom-name field (cols 12-16) as a fallback."""
    nm = name_field.strip()
    # Strip leading digits: "1HB", "2HD" etc. are hydrogen atoms
    nm = nm.lstrip("0123456789")
    alpha = "".join(c for c in nm if c.isalpha())[:2]
    if not alpha:
        return "X"
    if len(alpha) == 1:
        return alpha.upper()
    candidate = alpha[0].upper() + alpha[1].lower()
    # Accept two-letter symbol only if it's a known element; else fall back to one letter
    return candidate if candidate in VDW_RADII else alpha[0].upper()


def parse_pdb_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    mol = Molecule()
    mol.name = Path(filepath).stem
    serial_map = {}
    with open(filepath) as f:
        lines = f.readlines()
    idx = 0
    for line in lines:
        if line[:6].strip() in ("ATOM", "HETATM"):
            elem = line[76:78].strip()
            if not elem:
                elem = _pdb_element_from_name(line[12:16])
            mol.atoms.append(Atom(idx, elem, float(line[30:38]),
                                  float(line[38:46]), float(line[46:54])))
            serial_map[int(line[6:11])] = idx
            idx += 1
    seen = set()
    conect = False
    for line in lines:
        if line.startswith("CONECT"):
            conect = True
            parts = line[6:].split()
            if not parts:
                continue
            i1 = serial_map.get(int(parts[0]))
            if i1 is None:
                continue
            for s in parts[1:]:
                i2 = serial_map.get(int(s))
                if i2 is None:
                    continue
                k = (min(i1, i2), max(i1, i2))
                if k not in seen:
                    seen.add(k)
                    mol.bonds.append(Bond(i1, i2))
    if not conect:
        n = len(mol.atoms)
        for i in range(n):
            for j in range(i + 1, n):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))
    return mol


def load_molecule(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    ext = Path(filepath).suffix.lower()
    if ext in (".mol", ".sdf"):
        return parse_mol_file(filepath)
    elif ext == ".xyz":
        return parse_xyz_file(filepath, tol, min_bond_dist)
    elif ext == ".pdb":
        return parse_pdb_file(filepath, tol, min_bond_dist)
    elif ext in (".cjson", ".json"):
        return parse_cjson_file(filepath, tol, min_bond_dist)
    else:
        raise ValueError(f"Unsupported: {ext}. Use .mol .sdf .xyz .pdb .cjson .json")


def validate_molecule(mol):
    """
    Check for duplicate atom positions and duplicate bonds.
    Prints warnings; returns the number of problems found.
    """
    problems = 0

    # Duplicate atom positions (within 1e-4 Å)
    pos_seen = {}
    for a in mol.atoms:
        key = tuple(np.round(a.pos, 4))
        if key in pos_seen:
            print(f"  WARNING: atom {a.element}{a.index} shares position "
                  f"{key} with atom {pos_seen[key]} — coincident spheres")
            problems += 1
        else:
            pos_seen[key] = f"{a.element}{a.index}"

    # Duplicate bonds
    bond_seen = set()
    order_names = {1: "single", 2: "double", 3: "triple"}
    for b in mol.bonds:
        k = (min(b.atom1_idx, b.atom2_idx), max(b.atom1_idx, b.atom2_idx))
        if k in bond_seen:
            a1 = mol.atoms[b.atom1_idx]
            a2 = mol.atoms[b.atom2_idx]
            oname = order_names.get(b.order, f"order-{b.order}")
            print(f"  WARNING: duplicate {oname} bond "
                  f"{a1.element}[{b.atom1_idx}]-{a2.element}[{b.atom2_idx}]"
                  f" — coincident cylinders will corrupt boolean fuse")
            print(f"    {a1.element}[{b.atom1_idx}] @ "
                  f"({a1.x:.4f}, {a1.y:.4f}, {a1.z:.4f}) Å")
            print(f"    {a2.element}[{b.atom2_idx}] @ "
                  f"({a2.x:.4f}, {a2.y:.4f}, {a2.z:.4f}) Å")
            problems += 1
        else:
            bond_seen.add(k)

    return problems


# Atomic number → element symbol lookup (Z=1..96)
_Z_TO_SYMBOL = {
    1:"H", 2:"He", 3:"Li", 4:"Be", 5:"B", 6:"C", 7:"N", 8:"O",
    9:"F", 10:"Ne", 11:"Na", 12:"Mg", 13:"Al", 14:"Si", 15:"P",
    16:"S", 17:"Cl", 18:"Ar", 19:"K", 20:"Ca", 21:"Sc", 22:"Ti",
    23:"V", 24:"Cr", 25:"Mn", 26:"Fe", 27:"Co", 28:"Ni", 29:"Cu",
    30:"Zn", 31:"Ga", 32:"Ge", 33:"As", 34:"Se", 35:"Br", 36:"Kr",
    37:"Rb", 38:"Sr", 39:"Y", 40:"Zr", 41:"Nb", 42:"Mo", 43:"Tc",
    44:"Ru", 45:"Rh", 46:"Pd", 47:"Ag", 48:"Cd", 49:"In", 50:"Sn",
    51:"Sb", 52:"Te", 53:"I", 54:"Xe", 55:"Cs", 56:"Ba", 57:"La",
    58:"Ce", 59:"Pr", 60:"Nd", 61:"Pm", 62:"Sm", 63:"Eu", 64:"Gd",
    65:"Tb", 66:"Dy", 67:"Ho", 68:"Er", 69:"Tm", 70:"Yb", 71:"Lu",
    72:"Hf", 73:"Ta", 74:"W", 75:"Re", 76:"Os", 77:"Ir", 78:"Pt",
    79:"Au", 80:"Hg", 81:"Tl", 82:"Pb", 83:"Bi", 84:"Po", 85:"At",
    86:"Rn", 87:"Fr", 88:"Ra", 89:"Ac", 90:"Th", 91:"Pa", 92:"U",
    93:"Np", 94:"Pu", 95:"Am", 96:"Cm",
}


def parse_cjson_file(filepath, tol=0.4, min_bond_dist=MIN_BOND_DIST):
    """
    Parse an Avogadro2 Chemical JSON (CJSON) file.

    CJSON format (https://github.com/OpenChemistry/chemicaljson):
      {
        "chemicalJson": 1,        // or "chemical json": 0 for v0
        "name": "benzene",        // optional
        "atoms": {
          "elements": {
            "number": [6, 6, ...],     // atomic numbers
            "symbols": ["C", "C", ...] // optional, v1 only
          },
          "coords": {
            "3d": [x0, y0, z0, x1, y1, z1, ...]  // flat array, 3N
          }
        },
        "bonds": {                // optional
          "connections": {
            "index": [0, 1, 1, 2, ...]  // flat pairs: [a1,b1, a2,b2, ...]
          },
          "order": [2, 1, ...]    // bond orders
        }
      }

    If bonds are absent, they are inferred from covalent radii.
    Handles both CJSON v0 (spaces in keys) and v1 (camelCase).
    """
    mol = Molecule()
    with open(filepath) as f:
        data = json.load(f)

    # Validate it's CJSON
    if "chemicalJson" not in data and "chemical json" not in data:
        # Could be a plain JSON file — check for atoms key
        if "atoms" not in data:
            raise ValueError(
                f"{filepath}: not a recognized CJSON file "
                f"(missing 'chemicalJson' key and 'atoms' object)")

    mol.name = data.get("name", Path(filepath).stem)

    # --- Parse atoms ---
    atoms_obj = data.get("atoms", {})
    elements_obj = atoms_obj.get("elements", {})

    # Atomic numbers (required)
    atomic_numbers = elements_obj.get("number", [])

    # Element symbols (optional, v1 only) — prefer these if available
    symbols = elements_obj.get("symbols", [])

    # Coordinates: flat array [x0,y0,z0, x1,y1,z1, ...]
    coords_obj = atoms_obj.get("coords", {})
    coords_3d = coords_obj.get("3d", [])

    if not coords_3d:
        raise ValueError(f"{filepath}: no 3D coordinates found in "
                         f"atoms.coords.3d")

    num_atoms = len(coords_3d) // 3
    if len(coords_3d) != num_atoms * 3:
        raise ValueError(f"{filepath}: coords.3d length {len(coords_3d)} "
                         f"is not divisible by 3")

    if atomic_numbers and len(atomic_numbers) != num_atoms:
        raise ValueError(f"{filepath}: {len(atomic_numbers)} atomic numbers "
                         f"but {num_atoms} coordinate triples")

    for i in range(num_atoms):
        x = float(coords_3d[i * 3])
        y = float(coords_3d[i * 3 + 1])
        z = float(coords_3d[i * 3 + 2])

        # Determine element symbol
        if symbols and i < len(symbols):
            elem = symbols[i]
        elif atomic_numbers and i < len(atomic_numbers):
            z_num = int(atomic_numbers[i])
            elem = _Z_TO_SYMBOL.get(z_num, f"X{z_num}")
        else:
            elem = "X"

        mol.atoms.append(Atom(i, elem, x, y, z))

    # --- Parse bonds ---
    bonds_obj = data.get("bonds", {})
    connections = bonds_obj.get("connections", {})
    bond_indices = connections.get("index", [])
    bond_orders = bonds_obj.get("order", [])

    if bond_indices:
        num_bonds = len(bond_indices) // 2
        if len(bond_indices) != num_bonds * 2:
            print(f"  Warning: bonds.connections.index length "
                  f"{len(bond_indices)} not even, truncating")

        seen = set()
        for i in range(num_bonds):
            a1 = int(bond_indices[i * 2])
            a2 = int(bond_indices[i * 2 + 1])
            order = int(bond_orders[i]) if i < len(bond_orders) else 1
            if 0 <= a1 < num_atoms and 0 <= a2 < num_atoms:
                k = (min(a1, a2), max(a1, a2))
                if k in seen:
                    at1 = mol.atoms[a1]
                    at2 = mol.atoms[a2]
                    oname = {1: "single", 2: "double", 3: "triple"}.get(order, f"order-{order}")
                    print(f"  WARNING: duplicate {oname} bond in CJSON — "
                          f"keeping first, skipping this entry")
                    print(f"    {at1.element}[{a1}] @ "
                          f"({at1.x:.4f}, {at1.y:.4f}, {at1.z:.4f}) Å")
                    print(f"    {at2.element}[{a2}] @ "
                          f"({at2.x:.4f}, {at2.y:.4f}, {at2.z:.4f}) Å")
                    continue
                seen.add(k)
                mol.bonds.append(Bond(a1, a2, order))
    else:
        # No bond info — infer from covalent radii
        for i in range(num_atoms):
            for j in range(i + 1, num_atoms):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if min_bond_dist < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))

    return mol


# ═══════════════════════════════════════════════════════════════════════════
# CAD PRIMITIVES — no rotation math, uses Plane-based extrusion
# ═══════════════════════════════════════════════════════════════════════════

def _make_sphere(center_mm, radius_mm):
    """Create a solid sphere at center_mm with given radius."""
    import cadquery as cq
    s = cq.Workplane("XY").sphere(radius_mm)
    return s.translate(cq.Vector(center_mm[0], center_mm[1], center_mm[2]))


def _as_solid(shape):
    """Ensure shape is a cq.Solid, unwrapping or rebuilding as needed.

    BRepAlgoAPI_Fuse always returns TopoDS_Compound.  OCCT occasionally
    wraps the result as a closed Shell rather than a Solid.
    We handle both cases:
      1. Compound contains one Solid  → unwrap directly.
      2. Compound contains zero Solids but one closed Shell
         → rebuild a Solid via BRepBuilderAPI_MakeSolid.
    """
    solids = shape.Solids()
    if len(solids) == 1:
        return solids[0]
    if len(solids) == 0:
        shells = shape.Shells()
        if len(shells) == 1:
            from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeSolid
            import cadquery as cq
            ms = BRepBuilderAPI_MakeSolid(shells[0].wrapped)
            if ms.IsDone():
                return cq.Shape.cast(ms.Solid())
    return shape


def _make_cylinder(start_mm, end_mm, radius_mm):
    """
    Create a solid cylinder from start_mm to end_mm using Plane-based extrusion.
    Returns None for zero-length segments.
    """
    import cadquery as cq
    start = np.asarray(start_mm, dtype=float)
    end   = np.asarray(end_mm,   dtype=float)
    direction = end - start
    length = np.linalg.norm(direction)
    if length < 1e-6:
        return None

    nv     = direction / length
    normal = cq.Vector(nv[0], nv[1], nv[2])
    origin = cq.Vector(start[0], start[1], start[2])

    # xDir must be perpendicular to normal. Use Z unless bond is near-vertical,
    # then use X.  Threshold 1/√2 guarantees cross product is non-degenerate.
    ref      = np.array([0.0, 0.0, 1.0]) if abs(nv[2]) < 0.707 else np.array([1.0, 0.0, 0.0])
    x_dir_np = np.cross(nv, ref)
    x_dir_np /= np.linalg.norm(x_dir_np)
    x_dir    = cq.Vector(x_dir_np[0], x_dir_np[1], x_dir_np[2])

    plane = cq.Plane(origin=origin, normal=normal, xDir=x_dir)
    return cq.Workplane(plane).circle(radius_mm).extrude(length)


# ═══════════════════════════════════════════════════════════════════════════
# MODEL BUILDER
# ═══════════════════════════════════════════════════════════════════════════

def sphere_radius_mm(vdw_angstroms, scale, vdw_scale):
    """VdW radius → model sphere radius in mm."""
    return vdw_angstroms * vdw_scale * scale / 2.0


def tube_radius_mm(scale, bond_scale, override=None):
    """Compute bond tube radius from H VdW and scale factors."""
    if override is not None:
        return override
    return VDW_RADII["H"] * bond_scale * scale / 2.0


def validate_geometry(mol, scale, vdw_scale, bond_scale,
                      tube_radius_override=None):
    """
    Validate spatial contact between all spheres and tubes.
    Pure numpy — does NOT require CadQuery.
    """
    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    print("\n  ── Spatial contact validation ──")
    issues = 0

    for bond in mol.bonds:
        a1, a2 = mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]
        p1, p2 = a1.pos * scale, a2.pos * scale
        d = p2 - p1
        length = np.linalg.norm(d)
        if length < 0.01:
            print(f"  !! Zero-length bond {a1.element}{bond.atom1_idx}-"
                  f"{a2.element}{bond.atom2_idx}")
            issues += 1
            continue
        d_hat = d / length

        r1 = max(sphere_radius_mm(a1.vdw_radius, scale, vdw_scale),
                 t_r + MIN_EXCESS)
        r2 = max(sphere_radius_mm(a2.vdw_radius, scale, vdw_scale),
                 t_r + MIN_EXCESS)

        # Cylinder goes center-to-center (no extension)
        cyl_start = p1
        cyl_end = p2
        cyl_length = length

        raw = _bond_offsets(d_hat, bond.order, t_r)
        kind_label = "single" if bond.order == 1 else None
        offsets = [(off, cr, kind_label or f"multi-k{k}")
                   for k, (off, cr) in enumerate(raw)]

        for off, cr, kind in offsets:
            for label, center, sph_r in [
                (f"{a1.element}{bond.atom1_idx}", p1, r1),
                (f"{a2.element}{bond.atom2_idx}", p2, r2),
            ]:
                axis_origin = cyl_start + off
                v = center - axis_origin
                proj = np.dot(v, d_hat)
                closest = axis_origin + proj * d_hat
                axis_dist = np.linalg.norm(center - closest)

                # For center-to-center: atom center is at proj=0 or proj=length
                # The cylinder endpoint coincides with atom center
                # Overlap = sphere extends past cylinder end along axis
                # Overlap depth along axis = sph_r (for centered bonds)
                #                          = sqrt(sph_r^2 - axis_dist^2) for offset
                if axis_dist < sph_r:
                    depth = math.sqrt(sph_r**2 - axis_dist**2)
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    # Also check sphere excess over tube
                    excess = sph_r - cr
                    status = "OK" if (in_range and excess > 0) else \
                             "TANGENT" if (in_range and excess <= 0) else \
                             "AXIS_SHORT"
                elif axis_dist < sph_r + cr:
                    depth = 0
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    status = "PARTIAL" if in_range else "MISS"
                else:
                    depth = 0
                    status = "NO_CONTACT"
                    in_range = False

                ok = status == "OK"
                if not ok:
                    issues += 1
                sym = "  " if ok else ">>"
                off_mag = np.linalg.norm(off)
                off_s = f"off={off_mag:.2f}" if off_mag > 0.01 else "ctr"
                print(f"  {sym} {a1.element}{bond.atom1_idx}-"
                      f"{a2.element}{bond.atom2_idx} -> {label}: "
                      f"ax_d={axis_dist:.3f} sph_r={sph_r:.2f} "
                      f"cyl_r={cr:.2f} proj={proj:.1f}/{cyl_length:.1f} "
                      f"depth={depth:.2f} excess={sph_r-cr:.2f} "
                      f"{off_s} {kind} [{status}]")

    if issues:
        print(f"\n  !! {issues} issues found !!")
    else:
        print(f"\n  All {len(mol.bonds)} bonds validated — "
              f"sphere_r > tube_r at every junction.")
    return issues


def build_model(mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                tube_radius_override=None, fillet_size=None,
                no_fillet=False, add_base=False, base_thickness=3.0,
                base_margin=5.0, union_all=False):
    """
    Build ball-and-stick molecular model as a single fused BREP solid.

    All sphere and cylinder primitives are collected into a flat list and
    fused in one BRepAlgoAPI_Fuse call (multi-tool mode).

    --no-fillet : outputs overlapping sphere+cylinder primitives as a
                  Compound (no boolean, always valid STEP).
    --union     : accepted for backward compatibility; the default path
                  always produces a single fused solid.
    """
    if not mol.atoms:
        raise ValueError("Molecule has no atoms — nothing to build.")

    import cadquery as cq
    from OCP.BRepAlgoAPI import BRepAlgoAPI_Fuse
    from OCP.TopTools import TopTools_ListOfShape

    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    def atom_r(atom):
        return max(sphere_radius_mm(atom.vdw_radius, scale, vdw_scale),
                   t_r + MIN_EXCESS)

    # ── Sizing table ──────────────────────────────────────────────────────
    print(f"  Scale: {scale} mm/A  VdW: {vdw_scale}x  Bond: {bond_scale}x")
    print(f"  Tube radius: {t_r:.3f} mm")
    print()
    print(f"  {'Elem':4s}  {'sph_r':>7s}  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':4s}  {'-----':>7s}  {'-------':>8s}  {'-----':>7s}  ------")
    for elem in sorted(set(a.element for a in mol.atoms)):
        vdw = VDW_RADII.get(elem, DEFAULT_VDW_RADIUS)
        r   = max(sphere_radius_mm(vdw, scale, vdw_scale), t_r + MIN_EXCESS)
        ov  = r - t_r
        z   = math.sqrt(max(0.0, r*r - t_r*t_r))
        ang = math.degrees(math.asin(min(1.0, z / r)))
        st  = "ok" if ov >= 1.0 else ("marginal" if ov >= 0.3 else "GAP RISK")
        print(f"  {elem:4s}  {r:7.3f}  {ov:8.3f}  {ang:7.1f}  {st}")
    print()

    gap_count = 0
    for bond in mol.bonds:
        for atom in (mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]):
            if (atom_r(atom) - t_r) < 0.3:
                gap_count += 1
    if gap_count:
        print(f"  WARNING: {gap_count} junctions have overlap < 0.3 mm"
              f" -- reduce --bond-scale or raise --vdw-scale")
    else:
        print("  All junction overlaps >= 0.3 mm  (ok)")
    print()

    # ── Path 1: --no-fillet compound (validated, no boolean) ─────────────
    if no_fillet:
        shapes = []
        for atom in mol.atoms:
            pos = np.asarray(atom.pos * scale, dtype=float)
            shapes.append(_make_sphere(pos, atom_r(atom)).val())
        n_cyl = 0
        for bond in mol.bonds:
            a1 = mol.atoms[bond.atom1_idx]
            a2 = mol.atoms[bond.atom2_idx]
            p1 = np.asarray(a1.pos * scale, dtype=float)
            p2 = np.asarray(a2.pos * scale, dtype=float)
            L  = float(np.linalg.norm(p2 - p1))
            if L < 0.01:
                continue
            d = (p2 - p1) / L
            for off, cyl_r in _bond_offsets(d, bond.order, t_r):
                cyl = _make_cylinder(p1 + off, p2 + off, cyl_r)
                if cyl is not None:
                    shapes.append(cyl.val())
                    n_cyl += 1
        print(f"  Bodies: {len(mol.atoms)} spheres + {n_cyl} cylinders "
              f"(no boolean — overlapping primitives)")
        return cq.Compound.makeCompound(shapes)

    # ── Path 2: multi-tool fuse ───────────────────────────────────────────

    # Build all sphere and cylinder primitives as a flat list
    all_shapes = []

    for atom in mol.atoms:
        pos = np.asarray(atom.pos * scale, dtype=float)
        all_shapes.append(_make_sphere(pos, atom_r(atom)).val())

    n_cyl = 0
    for bond in mol.bonds:
        a1 = mol.atoms[bond.atom1_idx]
        a2 = mol.atoms[bond.atom2_idx]
        p1 = np.asarray(a1.pos * scale, dtype=float)
        p2 = np.asarray(a2.pos * scale, dtype=float)
        L  = float(np.linalg.norm(p2 - p1))
        if L < 0.01:
            continue
        d = (p2 - p1) / L
        for off, cyl_r in _bond_offsets(d, bond.order, t_r):
            cyl = _make_cylinder(p1 + off, p2 + off, cyl_r)
            if cyl is not None:
                all_shapes.append(cyl.val())
                n_cyl += 1

    print(f"  Primitives: {len(mol.atoms)} spheres + {n_cyl} cylinders")

    # Single multi-tool fuse: first shape is the argument, rest are tools.
    # One kernel call avoids the incremental pairwise STEP-export orientation bug.
    if len(all_shapes) == 1:
        result = all_shapes[0]
    else:
        print(f"  Fusing {len(all_shapes)} primitives...")
        arg_list  = TopTools_ListOfShape()
        tool_list = TopTools_ListOfShape()
        arg_list.Append(all_shapes[0].wrapped)
        for s in all_shapes[1:]:
            tool_list.Append(s.wrapped)

        fuser = BRepAlgoAPI_Fuse()
        fuser.SetArguments(arg_list)
        fuser.SetTools(tool_list)
        fuser.SetFuzzyValue(1e-6)
        fuser.Build()

        if not fuser.IsDone():
            print("  WARNING: multi-tool fuse failed — falling back to "
                  "--no-fillet compound")
            return cq.Compound.makeCompound(all_shapes)

        result = _as_solid(cq.Shape.cast(fuser.Shape()))
        print(f"  Fuse complete: {len(result.Faces())} faces, "
              f"{len(result.Edges())} edges")

    # ── Optional base plate ────────────────────────────────────────────────
    if add_base:
        max_r = max(atom_r(a) for a in mol.atoms)
        bb_min, bb_max = mol.bounding_box()
        bmin = np.asarray(bb_min * scale, dtype=float)
        bmax = np.asarray(bb_max * scale, dtype=float)
        z_bot = float(bmin[2]) - max_r - 0.5
        w  = float(bmax[0] - bmin[0]) + 2 * base_margin + 2 * max_r
        dd = float(bmax[1] - bmin[1]) + 2 * base_margin + 2 * max_r
        cx = float(bmin[0] + bmax[0]) / 2.0
        cy = float(bmin[1] + bmax[1]) / 2.0
        base_wp = (cq.Workplane("XY")
                   .box(w, dd, base_thickness)
                   .translate(cq.Vector(cx, cy, z_bot - base_thickness / 2.0)))
        try:
            base_wp = base_wp.edges("|Z").fillet(base_thickness * 0.4)
        except Exception:
            pass
        base_solid = base_wp.val()
        base_args  = TopTools_ListOfShape()
        base_args.Append(result.wrapped)
        base_tools = TopTools_ListOfShape()
        base_tools.Append(base_solid.wrapped)
        bf = BRepAlgoAPI_Fuse()
        bf.SetArguments(base_args)
        bf.SetTools(base_tools)
        bf.Build()
        if bf.IsDone():
            result = _as_solid(cq.Shape.cast(bf.Shape()))
        else:
            return cq.Compound.makeCompound([result, base_solid])

    return result


def check_step_gaps(step_file, mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                    tube_radius_override=None, n_samples=12, probe_depth=0.5):
    """
    Analytical junction geometry check against a STEP file.

    Computes sphere-tube overlap and junction angle for every bond endpoint
    directly from the model parameters -- no point-in-solid probing needed.

    overlap  = sphere_radius - tube_radius
               (how deeply the tube is embedded in the sphere)
    angle    = arcsin(sqrt(sphere_r^2 - tube_r^2) / sphere_r)
               (the angle between the bond axis and the sphere surface
                at the junction circle; 90deg = ideal, 0deg = tangent)

    Both metrics are purely geometric and computed instantly.  The STEP
    file is loaded only to verify that the expected number of hub bodies
    is present.

    Flags:
      GAP      -- overlap < 0.3 mm  OR  angle < 10 deg
      MARGINAL -- overlap < 1.0 mm  OR  angle < 20 deg
    """
    import cadquery as cq

    print("=" * 70)
    print(f"JUNCTION GEOMETRY CHECK  ({step_file})")
    print("=" * 70)

    # Load STEP and count bodies
    compound = None
    try:
        compound = cq.importers.importStep(str(step_file))
        n_bodies = len(compound.solids().vals())
        print(f"  STEP solid bodies: {n_bodies}  (molecule atoms: {len(mol.atoms)})")
    except Exception as exc:
        print(f"  Could not load STEP file: {exc}")

    t_r       = tube_radius_mm(scale, bond_scale, tube_radius_override)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    def atom_r(atom):
        return max(sphere_radius_mm(atom.vdw_radius, scale, vdw_scale),
                   t_r + MIN_EXCESS)

    print(f"  Tube radius: {t_r:.3f} mm")
    print()
    print(f"  {'Bond':22s}  {'end':>3s}  {'sph_r':>7s}"
          f"  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':22s}  {'---':>3s}  {'-----':>7s}"
          f"  {'-------':>8s}  {'-----':>7s}  ------")

    flags = []

    for bond in mol.bonds:
        a1    = mol.atoms[bond.atom1_idx]
        a2    = mol.atoms[bond.atom2_idx]
        r1, r2 = atom_r(a1), atom_r(a2)
        label  = f"{a1.element}{bond.atom1_idx}-{a2.element}{bond.atom2_idx}"

        for atom, r, end_lbl in [(a1, r1, "a1"), (a2, r2, "a2")]:
            if t_r >= r:
                print(f"  {label:22s}  {end_lbl:>3s}  DEGENERATE: tube_r >= sphere_r")
                flags.append((label, end_lbl, 0.0, 0.0, "GAP"))
                continue

            ov  = r - t_r
            z   = math.sqrt(r * r - t_r * t_r)
            ang = math.degrees(math.asin(min(1.0, z / r)))

            if ov < 0.3 or ang < 10.0:
                status = "GAP"
            elif ov < 1.0 or ang < 20.0:
                status = "MARGINAL"
            else:
                status = "ok"

            mark = "  <--" if status != "ok" else ""
            print(f"  {label:22s}  {end_lbl:>3s}  {r:7.3f}"
                  f"  {ov:8.3f}  {ang:7.1f}  {status}{mark}")

            if status != "ok":
                flags.append((label, end_lbl, ov, ang, status))

    print()
    if flags:
        print(f"  {len(flags)} junction(s) flagged:")
        for lbl, end, ov, ang, st in flags:
            print(f"    {lbl} ({end}):  overlap={ov:.3f} mm"
                  f"  angle={ang:.1f} deg  [{st}]")
    else:
        print("  All junctions ok.")

    # --- Spatial atom-presence check ---
    print()
    print("  ATOM PRESENCE CHECK")
    if compound is None:
        print("  (STEP file not loaded — skipped)")
    else:
        try:
            from OCP.BRepGProp import BRepGProp
            from OCP.GProp import GProp_GProps

            centroids = []
            for solid in compound.solids().vals():
                props = GProp_GProps()
                BRepGProp.VolumeProperties_s(solid.wrapped, props)
                c = props.CentreOfMass()
                centroids.append(np.array([c.X(), c.Y(), c.Z()]))

            centres_arr = np.array(centroids) if centroids else np.zeros((0, 3))
            THRESHOLD_MM = 0.5
            missing = []
            for atom in mol.atoms:
                expected_pos = np.asarray(atom.pos * scale, dtype=float)
                if len(centres_arr) == 0:
                    dist = float("inf")
                else:
                    dist = float(np.min(
                        np.linalg.norm(centres_arr - expected_pos, axis=1)))
                if dist > THRESHOLD_MM:
                    missing.append((atom.index, atom.element, dist,
                                    expected_pos))

            if missing:
                print(f"  WARNING: {len(missing)} atom(s) have no solid within "
                      f"{THRESHOLD_MM} mm of their expected position:")
                print(f"  {'Atom':10s}  {'nearest_mm':>10s}  expected_pos (mm)")
                for idx, elem, dist, epos in missing:
                    print(f"  {elem+str(idx):10s}  {dist:10.2f}  "
                          f"({epos[0]:.2f}, {epos[1]:.2f}, {epos[2]:.2f})")
            else:
                print(f"  All {len(mol.atoms)} atoms present.  (ok)")
        except Exception as exc:
            print(f"  Atom presence check failed: {exc}")

    print("=" * 70)


def check_solid_integrity(step_file, check_intersections=False):
    """
    Check BREP integrity of every solid in a STEP file using OCCT validators.

    Three checks are run per solid:
      1. BRepCheck_Analyzer          — topology & geometry validity (37 error codes)
      2. ShapeAnalysis_ShapeContents — free edges / faces (watertightness proxy)
      3. BRepGProp.VolumeProperties  — volume sign (negative = inverted orientation)

    Optional (slow, off by default):
      4. BRepAlgoAPI_Check           — self-intersection detection

    Issues are classified as:
      FATAL — would typically cause slicing to fail or produce broken prints
      WARN  — may cause problems depending on slicer tolerance

    Returns True if no fatal issues were found.
    """
    import cadquery as cq
    from OCP.BRepCheck import BRepCheck_Analyzer, BRepCheck_Status
    from OCP.ShapeAnalysis import ShapeAnalysis_ShapeContents
    from OCP.BRepGProp import BRepGProp
    from OCP.GProp import GProp_GProps
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopAbs import TopAbs_SHELL, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX

    # ── Classification tables (string-keyed for robustness across OCP versions) ──
    _FATAL_NAMES = {
        "BRepCheck_NotClosed",
        "BRepCheck_NotConnected",
        "BRepCheck_FreeEdge",
        "BRepCheck_SelfIntersectingWire",
        "BRepCheck_IntersectingWires",
        "BRepCheck_BadOrientation",
        "BRepCheck_BadOrientationOfSubshape",
        "BRepCheck_UnorientableShape",
        "BRepCheck_EmptyShell",
        "BRepCheck_EmptyWire",
        "BRepCheck_InvalidImbricationOfShells",
    }

    _DESC = {
        "BRepCheck_NotClosed":
            "shell not closed (open / not watertight)",
        "BRepCheck_NotConnected":
            "disconnected shell",
        "BRepCheck_FreeEdge":
            "free edge — belongs to only one face (non-manifold)",
        "BRepCheck_SelfIntersectingWire":
            "self-intersecting wire",
        "BRepCheck_IntersectingWires":
            "intersecting wires",
        "BRepCheck_BadOrientation":
            "bad face orientation (inverted normal)",
        "BRepCheck_BadOrientationOfSubshape":
            "bad sub-shape orientation",
        "BRepCheck_UnorientableShape":
            "unorientable shape",
        "BRepCheck_EmptyShell":
            "empty shell (no faces)",
        "BRepCheck_EmptyWire":
            "empty wire (no edges)",
        "BRepCheck_InvalidSameParameterFlag":
            "invalid same-parameter flag",
        "BRepCheck_InvalidSameRangeFlag":
            "invalid same-range flag",
        "BRepCheck_InvalidPointOnSurface":
            "invalid point on surface",
        "BRepCheck_InvalidPointOnCurve":
            "invalid point on curve",
        "BRepCheck_InvalidCurveOnSurface":
            "invalid curve on surface",
        "BRepCheck_CheckFail":
            "OCCT shape-check failed (internal error)",
        "BRepCheck_InvalidWire":
            "invalid wire",
        "BRepCheck_InvalidRange":
            "invalid parameter range",
        "BRepCheck_InvalidToleranceValue":
            "invalid tolerance value",
        "BRepCheck_RedundantEdge":
            "redundant edge",
        "BRepCheck_RedundantFace":
            "redundant face",
        "BRepCheck_InvalidImbricationOfShells":
            "invalid shell nesting",
        "BRepCheck_SubshapeNotInShape":
            "sub-shape not in parent shape",
    }

    def _status_name(s):
        """Extract 'BRepCheck_XxxYyy' string from an OCP enum value.

        OCP 7.8 formats the enum as 'BRepCheck_Status.BRepCheck_NotClosed'
        (no angle brackets); older or debug builds may include '<...>'.
        We take the last dot-separated component in all cases.
        """
        raw = str(s).strip("<>").split(":")[0].strip()
        return raw.split(".")[-1]

    def _collect_status_names(result):
        """Iterate a BRepCheck_ListOfStatus, return set of status name strings."""
        names = set()
        sl = result.Status()
        try:
            for s in sl:                    # OCP wraps most NCollection_List as iterable
                names.add(_status_name(s))
        except TypeError:
            # Fallback: 1-based Value() access
            for i in range(sl.Extent()):
                try:
                    names.add(_status_name(sl.Value(i + 1)))
                except Exception:
                    pass
        return names

    # ── Load file ─────────────────────────────────────────────────────────────
    print("=" * 70)
    print(f"SOLID INTEGRITY CHECK  ({step_file})")
    print("=" * 70)

    try:
        compound = cq.importers.importStep(str(step_file))
    except Exception as exc:
        print(f"  ERROR: Cannot load STEP file: {exc}")
        return False

    solids = compound.solids().vals()
    n_solids = len(solids)
    print(f"  Solids: {n_solids}")
    if n_solids == 0:
        print("  ERROR: No solids found in file.")
        return False
    print()

    global_fatal = 0
    global_warn  = 0
    global_ok    = 0
    # For large compounds, suppress OK-solid lines to avoid noise
    compact = n_solids > 20

    for idx, solid in enumerate(solids, 1):
        fatals = []   # (label, description) — would break slicing
        warns  = []   # (label, description) — slicer-dependent

        # ── Check 1: BRepCheck_Analyzer ───────────────────────────────
        try:
            ana = BRepCheck_Analyzer(solid.wrapped, True)
            if not ana.IsValid():
                seen = set()
                for sub_type in (TopAbs_SHELL, TopAbs_FACE,
                                  TopAbs_EDGE, TopAbs_VERTEX):
                    exp = TopExp_Explorer(solid.wrapped, sub_type)
                    while exp.More():
                        sub = exp.Current()
                        try:
                            seen |= _collect_status_names(ana.Result(sub))
                        except Exception:
                            pass
                        exp.Next()

                for name in seen:
                    if name == "BRepCheck_NoError":
                        continue
                    desc = _DESC.get(name, name)
                    if name in _FATAL_NAMES:
                        fatals.append((name, desc))
                    else:
                        warns.append((name, desc))
        except Exception as exc:
            warns.append(("BRepCheck_Analyzer", f"check raised: {exc}"))

        # ── Check 2: ShapeAnalysis_ShapeContents ──────────────────────
        n_shells = n_faces = free_edges = free_faces = 0
        try:
            contents = ShapeAnalysis_ShapeContents()
            contents.Perform(solid.wrapped)
            n_shells   = contents.NbShells()
            n_faces    = contents.NbFaces()
            free_edges = contents.NbFreeEdges()
            free_faces = contents.NbFreeFaces()
            if free_edges > 0:
                fatals.append(("FreeEdges",
                    f"{free_edges} free edge(s) — non-manifold / open shell"))
            if free_faces > 0:
                fatals.append(("FreeFaces",
                    f"{free_faces} free face(s) — disconnected geometry"))
        except Exception as exc:
            warns.append(("ShapeAnalysis", f"check raised: {exc}"))

        # ── Check 3: Volume sign ──────────────────────────────────────
        vol_str = "?"
        try:
            props = GProp_GProps()
            BRepGProp.VolumeProperties_s(solid.wrapped, props)
            vol = props.Mass()
            vol_str = f"{vol:.1f} mm³"
            if vol < 0:
                fatals.append(("NegativeVolume",
                    f"volume = {vol:.2f} mm³ — faces oriented inward"))
            elif vol == 0:
                fatals.append(("ZeroVolume", "zero volume — degenerate solid"))
        except Exception as exc:
            warns.append(("Volume", f"check raised: {exc}"))

        # ── Check 4: Self-intersection (optional) ─────────────────────
        if check_intersections:
            try:
                from OCP.BRepAlgoAPI import BRepAlgoAPI_Check
                chk = BRepAlgoAPI_Check(solid.wrapped, False, True)
                chk.Perform()
                if not chk.IsValid():
                    fatals.append(("SelfIntersection",
                        "solid self-intersects (BRepAlgoAPI_Check)"))
            except Exception as exc:
                warns.append(("SelfIntersection", f"check raised: {exc}"))

        # ── Per-solid report ──────────────────────────────────────────
        tag = "FAIL" if fatals else ("WARN" if warns else "OK  ")
        if fatals or warns:
            print(f"  [{tag}] solid {idx:3d}/{n_solids}"
                  f"  vol={vol_str}  shells={n_shells}  faces={n_faces}")
            for lbl, desc in sorted(set(fatals)):
                print(f"           FATAL  {lbl}: {desc}")
            for lbl, desc in sorted(set(warns)):
                print(f"           WARN   {lbl}: {desc}")
        elif not compact:
            print(f"  [{tag}] solid {idx:3d}/{n_solids}"
                  f"  vol={vol_str}  shells={n_shells}  faces={n_faces}")
        else:
            global_ok += 1

        global_fatal += len(fatals)
        global_warn  += len(warns)

    # ── Summary ───────────────────────────────────────────────────────
    if global_ok:
        print(f"  [OK  ] ({global_ok} solid(s) with no issues — omitted)")
    print()
    if global_fatal:
        print(f"  RESULT: {global_fatal} fatal issue(s), {global_warn} warning(s)"
              f" across {n_solids} solid(s).")
        print("  Slicing is likely to fail.  Recommended actions:")
        print("    • Re-run with --union to fuse all hubs into one manifold solid.")
        print("    • Open in FreeCAD → Part → Check Geometry for an interactive report.")
        print("    • Use MeshMixer or Netfabb repair on the STL export.")
    elif global_warn:
        print(f"  RESULT: 0 fatal, {global_warn} warning(s).  "
              "File may import with slicer warnings.")
    else:
        print(f"  RESULT: All {n_solids} solid(s) passed.  "
              "File should slice cleanly.")
    print("=" * 70)
    return global_fatal == 0


def export_model(shape, filepath, fmt="step"):
    """Export a CadQuery Shape/Compound/Assembly to STEP or STL."""
    import cadquery as cq
    is_assembly = isinstance(shape, cq.Assembly)
    if fmt in ("step", "stp"):
        if is_assembly:
            shape.save(filepath, exportType="STEP")
        else:
            cq.exporters.export(shape, filepath, exportType="STEP")
    elif fmt == "stl":
        src = shape.toCompound() if is_assembly else shape
        cq.exporters.export(src, filepath, exportType="STL",
                            tolerance=0.01, angularTolerance=0.1)
    else:
        raise ValueError(f"Unsupported format: {fmt}")


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(
        prog="mol2step.py",
        description=(
            "Generate solid BREP CAD files (STEP or STL) of ball-and-stick\n"
            "molecular models from molecular geometry files.\n\n"
            "Architecture: all sphere and cylinder primitives fused in one\n"
            "BRepAlgoAPI_Fuse call (multi-tool mode) to produce a single\n"
            "BREP solid.  Use --no-fillet for a compound of overlapping\n"
            "primitives (no boolean, always valid STEP)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=r"""
SCALE CONVENTION
  All distances are in mm.  Angstrom positions are multiplied by --scale.

  Atom sphere diameter  =  VdW_radius(A) * --vdw-scale * --scale
                        =  1 A  ->  1 cm diameter  (at defaults)

  Bond tube diameter    =  VdW_H(1.2 A) * --bond-scale * --scale
                        =  defaults give 8.4 mm diameter (bond-scale 0.7)

JUNCTION GEOMETRY
  At each sphere-tube junction the key metrics are:
    overlap  = sphere_radius - tube_radius  (tube embedded this far in sphere)
    angle    = arcsin(sqrt(r^2 - t^2) / r)  (surface meeting angle; 90=ideal)
  Both are printed at build time.  overlap < 0.3 mm or angle < 10 deg will
  produce visible seam artefacts.  Use --check-step to inspect after building.

INPUT FORMATS
  .mol / .sdf   MDL Molfile — explicit bond table, best choice
  .xyz          XYZ coordinates — bonds inferred from covalent radii + tolerance
  .pdb          PDB — CONECT records used; falls back to distance inference
  .cjson        Chemical JSON (Avogadro2 native format)

OUTPUT
  Default: <input_stem>.step  (STEP AP214, true BREP solid geometry)
  With --format stl: triangulated mesh for direct slicing

WORKFLOW
  1.  Obtain geometry:
        Avogadro2  ->  File > Export > Molecule (.cjson or .mol)
        PubChem    ->  Download > SDF (rename .sdf -> .mol, or use as-is)
        OpenBabel  ->  obabel input.pdb -O output.mol --gen3d

  2.  Generate STEP:
        python mol2step.py molecule.cjson -o molecule.step

  3.  Check for gaps (optional):
        python mol2step.py molecule.cjson --check-step molecule.step

  4.  Open in FreeCAD or OnShape:
        Inspect solid, add support struts or base plate as needed

  5.  Export STL / 3MF and slice in PrusaSlicer

EXAMPLES
  # Basic — defaults (vdw-scale 1.0, bond-scale 0.7)
  python mol2step.py caffeine.cjson -o caffeine.step

  # Smaller atoms and thinner bonds (good for larger molecules)
  python mol2step.py molecule.cjson --vdw-scale 0.7 --bond-scale 0.5

  # Print sizing table without building
  python mol2step.py molecule.cjson --info

  # Check junction geometry of an existing STEP file
  python mol2step.py molecule.cjson --check-step molecule.step

  # Add a base plate for bed adhesion
  python mol2step.py molecule.cjson --add-base --base-thickness 3.0

  # STL output (for direct slicing without CAD step)
  python mol2step.py molecule.cjson -o molecule.stl --format stl

  # Verbose bond/geometry validation
  python mol2step.py molecule.cjson --debug --info

PARAMETER GUIDE FOR 3D PRINTING
  Parameter        Default   Notes
  ───────────────────────────────────────────────────────────────────
  --scale          10.0      mm per Angstrom; increase for larger print
  --vdw-scale      1.0       atom sphere size multiplier
  --bond-scale     0.7       bond tube size multiplier (0.5-0.7 recommended)
  --bond-tolerance 0.4       Angstrom tolerance for bond inference (XYZ/PDB)

  Rule of thumb: bond-scale 0.5-0.7 keeps tubes noticeably thinner than atom
  spheres, which eliminates near-tangent junction artefacts.  The junction
  overlap and angle are printed at build time — look for "ok" on all elements.
""")

    # Positional — optional when --check-integrity is the only goal
    p.add_argument("input", nargs="?", default=None,
                   help="Molecule file (.mol .sdf .xyz .pdb .cjson); "
                        "not required when using --check-integrity alone")

    # Output
    p.add_argument("-o", "--output",
                   help="Output file path (default: <input_stem>.step or .stl)")
    p.add_argument("-f", "--format", choices=["step", "stp", "stl"],
                   default="step",
                   help="Output format: step (default), stp, or stl")

    # Scale
    p.add_argument("--scale", type=float, default=10.0,
                   help="Position scale in mm/Angstrom (default: 10.0)")
    p.add_argument("--vdw-scale", type=float, default=1.0,
                   help="Atom sphere radius multiplier (default: 1.0)")
    p.add_argument("--bond-scale", type=float, default=0.7,
                   help="Bond tube radius multiplier (default: 0.7; "
                        "keeps tubes thinner than H spheres to avoid gaps)")

    # Geometry overrides
    p.add_argument("--tube-radius", type=float, default=None,
                   help="Hard-override tube radius in mm (overrides --bond-scale)")
    p.add_argument("--no-fillet", action="store_true",
                   help="Export raw overlapping sphere+cylinder compound "
                        "(no boolean union)")
    p.add_argument("--union", action="store_true",
                   help="Boolean-union all hub solids into a single solid before "
                        "export (slower but produces one manifold body)")
    p.add_argument("--bond-tolerance", type=float, default=0.4,
                   help="Bond-inference distance tolerance in Angstroms "
                        "for XYZ/PDB files (default: 0.4)")
    p.add_argument("--min-bond-dist", type=float, default=MIN_BOND_DIST,
                   help=f"Minimum interatomic distance (Å) treated as a bond "
                        f"during inference (default: {MIN_BOND_DIST})")

    # Base plate
    p.add_argument("--add-base", action="store_true",
                   help="Add a rectangular base plate for bed adhesion")
    p.add_argument("--base-thickness", type=float, default=3.0,
                   help="Base plate thickness in mm (default: 3.0)")
    p.add_argument("--base-margin", type=float, default=5.0,
                   help="Base plate margin beyond molecule extent in mm "
                        "(default: 5.0)")

    # Misc
    p.add_argument("--no-center", action="store_true",
                   help="Do not translate molecule to origin before building")
    p.add_argument("--info", action="store_true",
                   help="Print atom/tube sizing table and exit (no build)")
    p.add_argument("--debug", action="store_true",
                   help="Run verbose geometry validation (bond lengths, "
                        "sphere/tube clearances) and print report")

    # Gap check
    p.add_argument("--check-step", metavar="STEP_FILE",
                   help="Analyse junction geometry (overlap and angle) for "
                        "every bond endpoint in STEP_FILE and report; "
                        "also verifies body count.  No build needed.")
    p.add_argument("--check-integrity", metavar="STEP_FILE",
                   help="Run OCCT BREP integrity checks on STEP_FILE: topology "
                        "validity (BRepCheck_Analyzer), free edges/faces "
                        "(ShapeAnalysis), and volume sign.  Reports FATAL / WARN "
                        "issues per solid.  No build needed.")
    p.add_argument("--check-self-intersect", action="store_true",
                   help="Add self-intersection test to --check-integrity "
                        "(slow: O(n²) in face count; use on small files only)")
    p.add_argument("--probe-depth", type=float, default=0.5,
                   help=argparse.SUPPRESS)   # legacy, kept for compat
    p.add_argument("--probe-samples", type=int, default=12,
                   help=argparse.SUPPRESS)   # legacy, kept for compat

    args = p.parse_args()

    # --check-integrity doesn't need a molecule file
    if args.check_integrity and args.input is None:
        check_solid_integrity(args.check_integrity,
                              check_intersections=args.check_self_intersect)
        return

    if args.input is None:
        p.error("input file is required unless --check-integrity is used alone")

    print(f"Loading: {args.input}")
    mol = load_molecule(args.input, args.bond_tolerance, args.min_bond_dist)
    if validate_molecule(mol) > 0:
        print("  (warnings above may cause geometry errors — review input file)")
    if not args.no_center:
        mol.center_on_origin()

    t_r = tube_radius_mm(args.scale, args.bond_scale, args.tube_radius)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    bb_min, bb_max = mol.bounding_box()
    ext = (bb_max - bb_min) * args.scale

    print(f"  Name: {mol.name}")
    print(f"  Atoms: {len(mol.atoms)}  Bonds: {len(mol.bonds)}")
    print(f"  VdW scale: {args.vdw_scale}x  Bond scale: {args.bond_scale}x")

    elems = sorted(set(a.element for a in mol.atoms))
    print(f"\n  {'Elem':4s}  {'VdW(A)':>6s}  {'r(mm)':>7s}  {'d(mm)':>7s}")
    print(f"  {'----':4s}  {'------':>6s}  {'-----':>7s}  {'-----':>7s}")
    for e in elems:
        vdw = VDW_RADII.get(e, DEFAULT_VDW_RADIUS)
        r = max(sphere_radius_mm(vdw, args.scale, args.vdw_scale),
                t_r + MIN_EXCESS)
        print(f"  {e:4s}  {vdw:6.2f}  {r:7.2f}  {r*2:7.2f}")
    print(f"  {'tube':4s}  {VDW_RADII['H']:6.2f}  {t_r:7.2f}  {t_r*2:7.2f}")
    print(f"\n  Bounding box: {bb_min.round(2)} to {bb_max.round(2)} A")
    print(f"  Model extent: {ext[0]:.1f} x {ext[1]:.1f} x {ext[2]:.1f} mm")

    if args.check_step:
        check_step_gaps(args.check_step, mol,
                        args.scale, args.vdw_scale, args.bond_scale,
                        args.tube_radius,
                        n_samples=args.probe_samples,
                        probe_depth=args.probe_depth)
        return

    if args.check_integrity:
        check_solid_integrity(args.check_integrity,
                              check_intersections=args.check_self_intersect)
        return

    if args.debug:
        validate_geometry(mol, args.scale, args.vdw_scale, args.bond_scale,
                          args.tube_radius)

    if args.info:
        return

    if not mol.bonds:
        print("\nERROR: No bonds found.  For XYZ/PDB files try "
              "--bond-tolerance 0.5")
        sys.exit(1)

    if args.output is None:
        stem = Path(args.input).stem
        args.output = f"{stem}.{'stl' if args.format == 'stl' else 'step'}"

    print(f"\nBuilding model...")
    shape = build_model(
        mol, args.scale, args.vdw_scale, args.bond_scale,
        args.tube_radius, None, args.no_fillet,
        args.add_base, args.base_thickness, args.base_margin,
        args.union)

    print(f"  Exporting: {args.output}")
    export_model(shape, args.output, args.format)
    print(f"Done -> {args.output}")
    if args.no_fillet:
        print(f"\n  The STEP compound contains one body per sphere/cylinder.")
        print(f"  To get a single solid in CAD:")
        print(f"    FreeCAD : select all bodies -> Part -> Boolean -> Union")
        print(f"    OnShape : select all -> Boolean -> Union")
    else:
        print(f"\n  Output is a single fused solid.")


if __name__ == "__main__":
    main()
