#!/usr/bin/env python3
"""
mol2step.py — Generate solid STEP/STL CAD files of ball-and-stick molecular
models from molecular geometry files (MOL/SDF, XYZ, PDB).

Atom spheres are sized by van der Waals radius. Bond tubes are sized by
the van der Waals radius of hydrogen. Sphere–tube intersections are
automatically filleted for printability.

Produces true solid BREP geometry that imports into OnShape, FreeCAD, or
any STEP-compatible CAD program.

Requirements:
    conda/mamba install -c conda-forge cadquery numpy

Usage:
    python mol2step.py molecule.mol -o molecule.step
    python mol2step.py molecule.mol --vdw-scale 0.5 --bond-scale 0.3
    python mol2step.py molecule.mol --debug   # verbose geometry validation

Scale convention (default --scale 10):
    1 Å VdW radius  →  1 cm sphere diameter
    Bond tubes sized to H VdW × bond-scale

Author: Generated by Claude for foton's molecular printing workflow
License: Public domain / CC0
"""

import argparse
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np

# ═══════════════════════════════════════════════════════════════════════════
# DATA TABLES
# ═══════════════════════════════════════════════════════════════════════════

# Van der Waals radii (Å) — 96 elements, Z=1..96
# Mantina et al., J. Phys. Chem. A 2009, 113, 5806 (main group)
# Alvarez, Dalton Trans. 2013, 42, 8617 (d-block, f-block)
# Bondi, J. Phys. Chem. 1964, 68, 441 (original)
VDW_RADII = {
    "H":  1.20, "He": 1.40,
    "Li": 1.81, "Be": 1.53, "B":  1.92, "C":  1.70, "N":  1.55,
    "O":  1.52, "F":  1.47, "Ne": 1.54,
    "Na": 2.27, "Mg": 1.73, "Al": 1.84, "Si": 2.10, "P":  1.80,
    "S":  1.80, "Cl": 1.75, "Ar": 1.88,
    "K":  2.75, "Ca": 2.31,
    "Sc": 2.15, "Ti": 2.11, "V":  2.07, "Cr": 2.06, "Mn": 2.05,
    "Fe": 2.04, "Co": 2.00, "Ni": 1.97, "Cu": 1.96, "Zn": 2.01,
    "Ga": 1.87, "Ge": 2.11, "As": 1.85, "Se": 1.90, "Br": 1.83,
    "Kr": 2.02,
    "Rb": 3.03, "Sr": 2.49,
    "Y":  2.32, "Zr": 2.23, "Nb": 2.18, "Mo": 2.17, "Tc": 2.16,
    "Ru": 2.13, "Rh": 2.10, "Pd": 2.10, "Ag": 2.11, "Cd": 2.18,
    "In": 1.93, "Sn": 2.17, "Sb": 2.06, "Te": 2.06, "I":  1.98,
    "Xe": 2.16,
    "Cs": 3.43, "Ba": 2.68,
    "La": 2.43, "Ce": 2.42, "Pr": 2.40, "Nd": 2.39, "Pm": 2.38,
    "Sm": 2.36, "Eu": 2.35, "Gd": 2.34, "Tb": 2.33, "Dy": 2.31,
    "Ho": 2.30, "Er": 2.29, "Tm": 2.27, "Yb": 2.26, "Lu": 2.24,
    "Hf": 2.23, "Ta": 2.22, "W":  2.18, "Re": 2.16, "Os": 2.16,
    "Ir": 2.13, "Pt": 2.13, "Au": 2.14, "Hg": 2.23,
    "Tl": 1.96, "Pb": 2.02, "Bi": 2.07, "Po": 1.97, "At": 2.02,
    "Rn": 2.20,
    "Fr": 3.48, "Ra": 2.83,
    "Ac": 2.47, "Th": 2.45, "Pa": 2.43, "U":  2.41, "Np": 2.39,
    "Pu": 2.43, "Am": 2.44, "Cm": 2.45,
}
DEFAULT_VDW_RADIUS = 2.00

# Covalent radii (Å) for bond inference — Cordero et al., Dalton Trans. 2008
COVALENT_RADII = {
    "H":  0.31, "He": 0.28,
    "Li": 1.28, "Be": 0.96, "B":  0.84, "C":  0.76, "N":  0.71,
    "O":  0.66, "F":  0.57, "Ne": 0.58,
    "Na": 1.66, "Mg": 1.41, "Al": 1.21, "Si": 1.11, "P":  1.07,
    "S":  1.05, "Cl": 1.02, "Ar": 1.06,
    "K":  2.03, "Ca": 1.76,
    "Sc": 1.70, "Ti": 1.60, "V":  1.53, "Cr": 1.39, "Mn": 1.39,
    "Fe": 1.32, "Co": 1.26, "Ni": 1.24, "Cu": 1.32, "Zn": 1.22,
    "Ga": 1.22, "Ge": 1.20, "As": 1.19, "Se": 1.20, "Br": 1.20,
    "Kr": 1.16,
    "Rb": 2.20, "Sr": 1.95,
    "Y":  1.90, "Zr": 1.75, "Nb": 1.64, "Mo": 1.54, "Tc": 1.47,
    "Ru": 1.46, "Rh": 1.42, "Pd": 1.39, "Ag": 1.45, "Cd": 1.44,
    "In": 1.42, "Sn": 1.39, "Sb": 1.39, "Te": 1.38, "I":  1.39,
    "Xe": 1.40,
    "Cs": 2.44, "Ba": 2.15,
    "La": 2.07, "Ce": 2.04, "Pr": 2.03, "Nd": 2.01, "Pm": 1.99,
    "Sm": 1.98, "Eu": 1.98, "Gd": 1.96, "Tb": 1.94, "Dy": 1.92,
    "Ho": 1.92, "Er": 1.89, "Tm": 1.90, "Yb": 1.87, "Lu": 1.87,
    "Hf": 1.75, "Ta": 1.70, "W":  1.62, "Re": 1.51, "Os": 1.44,
    "Ir": 1.41, "Pt": 1.36, "Au": 1.36, "Hg": 1.32,
    "Tl": 1.45, "Pb": 1.46, "Bi": 1.48, "Po": 1.40, "At": 1.50,
    "Rn": 1.50,
    "Fr": 2.60, "Ra": 2.21,
    "Ac": 2.15, "Th": 2.06, "Pa": 2.00, "U":  1.96, "Np": 1.90,
    "Pu": 1.87, "Am": 1.80, "Cm": 1.69,
}
DEFAULT_COVALENT_RADIUS = 1.50


# ═══════════════════════════════════════════════════════════════════════════
# MOLECULE DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class Atom:
    index: int
    element: str
    x: float
    y: float
    z: float

    @property
    def pos(self):
        return np.array([self.x, self.y, self.z])

    @property
    def vdw_radius(self):
        return VDW_RADII.get(self.element, DEFAULT_VDW_RADIUS)

    @property
    def covalent_radius(self):
        return COVALENT_RADII.get(self.element, DEFAULT_COVALENT_RADIUS)


@dataclass
class Bond:
    atom1_idx: int
    atom2_idx: int
    order: int = 1


@dataclass
class Molecule:
    name: str = "molecule"
    atoms: list = field(default_factory=list)
    bonds: list = field(default_factory=list)

    def center_on_origin(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        com = coords.mean(axis=0)
        for a in self.atoms:
            a.x -= com[0]; a.y -= com[1]; a.z -= com[2]

    def bounding_box(self):
        coords = np.array([[a.x, a.y, a.z] for a in self.atoms])
        return coords.min(axis=0), coords.max(axis=0)


# ═══════════════════════════════════════════════════════════════════════════
# FILE PARSERS
# ═══════════════════════════════════════════════════════════════════════════

def parse_mol_file(filepath):
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    mol.name = lines[0].strip() or Path(filepath).stem
    counts = lines[3].split()
    na, nb = int(counts[0]), int(counts[1])
    for i in range(na):
        p = lines[4 + i].split()
        mol.atoms.append(Atom(i, p[3].strip(), float(p[0]), float(p[1]), float(p[2])))
    for i in range(nb):
        p = lines[4 + na + i].split()
        mol.bonds.append(Bond(int(p[0]) - 1, int(p[1]) - 1, int(p[2])))
    return mol


def parse_xyz_file(filepath, tol=0.4):
    mol = Molecule()
    with open(filepath) as f:
        lines = f.readlines()
    na = int(lines[0].strip())
    mol.name = lines[1].strip() or Path(filepath).stem
    for i in range(na):
        p = lines[2 + i].split()
        elem = p[0][0].upper() + p[0][1:].lower() if len(p[0]) > 1 else p[0].upper()
        mol.atoms.append(Atom(i, elem, float(p[1]), float(p[2]), float(p[3])))
    for i in range(na):
        for j in range(i + 1, na):
            ai, aj = mol.atoms[i], mol.atoms[j]
            d = np.linalg.norm(ai.pos - aj.pos)
            if 0.4 < d < ai.covalent_radius + aj.covalent_radius + tol:
                mol.bonds.append(Bond(i, j))
    return mol


def parse_pdb_file(filepath, tol=0.4):
    mol = Molecule()
    mol.name = Path(filepath).stem
    serial_map = {}
    with open(filepath) as f:
        lines = f.readlines()
    idx = 0
    for line in lines:
        if line[:6].strip() in ("ATOM", "HETATM"):
            elem = line[76:78].strip()
            if not elem:
                nm = line[12:16].strip()
                elem = "".join(c for c in nm if c.isalpha())[:2]
                elem = elem[0].upper() + elem[1:].lower() if len(elem) > 1 else elem.upper()
            mol.atoms.append(Atom(idx, elem, float(line[30:38]),
                                  float(line[38:46]), float(line[46:54])))
            serial_map[int(line[6:11])] = idx
            idx += 1
    seen = set()
    conect = False
    for line in lines:
        if line.startswith("CONECT"):
            conect = True
            parts = line[6:].split()
            if not parts: continue
            i1 = serial_map.get(int(parts[0]))
            if i1 is None: continue
            for s in parts[1:]:
                i2 = serial_map.get(int(s))
                if i2 is None: continue
                k = (min(i1, i2), max(i1, i2))
                if k not in seen:
                    seen.add(k)
                    mol.bonds.append(Bond(i1, i2))
    if not conect:
        n = len(mol.atoms)
        for i in range(n):
            for j in range(i + 1, n):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if 0.4 < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))
    return mol


def load_molecule(filepath, tol=0.4):
    ext = Path(filepath).suffix.lower()
    if ext in (".mol", ".sdf"):   return parse_mol_file(filepath)
    elif ext == ".xyz":           return parse_xyz_file(filepath, tol)
    elif ext == ".pdb":           return parse_pdb_file(filepath, tol)
    elif ext in (".cjson", ".json"):  return parse_cjson_file(filepath, tol)
    else: raise ValueError(
        f"Unsupported: {ext}. Use .mol .sdf .xyz .pdb .cjson .json")


# Atomic number → element symbol lookup (Z=1..96)
_Z_TO_SYMBOL = {
    1:"H", 2:"He", 3:"Li", 4:"Be", 5:"B", 6:"C", 7:"N", 8:"O",
    9:"F", 10:"Ne", 11:"Na", 12:"Mg", 13:"Al", 14:"Si", 15:"P",
    16:"S", 17:"Cl", 18:"Ar", 19:"K", 20:"Ca", 21:"Sc", 22:"Ti",
    23:"V", 24:"Cr", 25:"Mn", 26:"Fe", 27:"Co", 28:"Ni", 29:"Cu",
    30:"Zn", 31:"Ga", 32:"Ge", 33:"As", 34:"Se", 35:"Br", 36:"Kr",
    37:"Rb", 38:"Sr", 39:"Y", 40:"Zr", 41:"Nb", 42:"Mo", 43:"Tc",
    44:"Ru", 45:"Rh", 46:"Pd", 47:"Ag", 48:"Cd", 49:"In", 50:"Sn",
    51:"Sb", 52:"Te", 53:"I", 54:"Xe", 55:"Cs", 56:"Ba", 57:"La",
    58:"Ce", 59:"Pr", 60:"Nd", 61:"Pm", 62:"Sm", 63:"Eu", 64:"Gd",
    65:"Tb", 66:"Dy", 67:"Ho", 68:"Er", 69:"Tm", 70:"Yb", 71:"Lu",
    72:"Hf", 73:"Ta", 74:"W", 75:"Re", 76:"Os", 77:"Ir", 78:"Pt",
    79:"Au", 80:"Hg", 81:"Tl", 82:"Pb", 83:"Bi", 84:"Po", 85:"At",
    86:"Rn", 87:"Fr", 88:"Ra", 89:"Ac", 90:"Th", 91:"Pa", 92:"U",
    93:"Np", 94:"Pu", 95:"Am", 96:"Cm",
}


def parse_cjson_file(filepath, tol=0.4):
    """
    Parse an Avogadro2 Chemical JSON (CJSON) file.

    CJSON format (https://github.com/OpenChemistry/chemicaljson):
      {
        "chemicalJson": 1,        // or "chemical json": 0 for v0
        "name": "benzene",        // optional
        "atoms": {
          "elements": {
            "number": [6, 6, ...],     // atomic numbers
            "symbols": ["C", "C", ...] // optional, v1 only
          },
          "coords": {
            "3d": [x0, y0, z0, x1, y1, z1, ...]  // flat array, 3N
          }
        },
        "bonds": {                // optional
          "connections": {
            "index": [0, 1, 1, 2, ...]  // flat pairs: [a1,b1, a2,b2, ...]
          },
          "order": [2, 1, ...]    // bond orders
        }
      }

    If bonds are absent, they are inferred from covalent radii.
    Handles both CJSON v0 (spaces in keys) and v1 (camelCase).
    """
    import json

    mol = Molecule()
    with open(filepath) as f:
        data = json.load(f)

    # Validate it's CJSON
    if "chemicalJson" not in data and "chemical json" not in data:
        # Could be a plain JSON file — check for atoms key
        if "atoms" not in data:
            raise ValueError(
                f"{filepath}: not a recognized CJSON file "
                f"(missing 'chemicalJson' key and 'atoms' object)")

    mol.name = data.get("name", Path(filepath).stem)

    # --- Parse atoms ---
    atoms_obj = data.get("atoms", {})
    elements_obj = atoms_obj.get("elements", {})

    # Atomic numbers (required)
    atomic_numbers = elements_obj.get("number", [])

    # Element symbols (optional, v1 only) — prefer these if available
    symbols = elements_obj.get("symbols", [])

    # Coordinates: flat array [x0,y0,z0, x1,y1,z1, ...]
    coords_obj = atoms_obj.get("coords", {})
    coords_3d = coords_obj.get("3d", [])

    if not coords_3d:
        raise ValueError(f"{filepath}: no 3D coordinates found in "
                         f"atoms.coords.3d")

    num_atoms = len(coords_3d) // 3
    if len(coords_3d) != num_atoms * 3:
        raise ValueError(f"{filepath}: coords.3d length {len(coords_3d)} "
                         f"is not divisible by 3")

    if atomic_numbers and len(atomic_numbers) != num_atoms:
        raise ValueError(f"{filepath}: {len(atomic_numbers)} atomic numbers "
                         f"but {num_atoms} coordinate triples")

    for i in range(num_atoms):
        x = float(coords_3d[i * 3])
        y = float(coords_3d[i * 3 + 1])
        z = float(coords_3d[i * 3 + 2])

        # Determine element symbol
        if symbols and i < len(symbols):
            elem = symbols[i]
        elif atomic_numbers and i < len(atomic_numbers):
            z_num = int(atomic_numbers[i])
            elem = _Z_TO_SYMBOL.get(z_num, f"X{z_num}")
        else:
            elem = "X"

        mol.atoms.append(Atom(i, elem, x, y, z))

    # --- Parse bonds ---
    bonds_obj = data.get("bonds", {})
    connections = bonds_obj.get("connections", {})
    bond_indices = connections.get("index", [])
    bond_orders = bonds_obj.get("order", [])

    if bond_indices:
        num_bonds = len(bond_indices) // 2
        if len(bond_indices) != num_bonds * 2:
            print(f"  Warning: bonds.connections.index length "
                  f"{len(bond_indices)} not even, truncating")

        for i in range(num_bonds):
            a1 = int(bond_indices[i * 2])
            a2 = int(bond_indices[i * 2 + 1])
            order = int(bond_orders[i]) if i < len(bond_orders) else 1
            if 0 <= a1 < num_atoms and 0 <= a2 < num_atoms:
                mol.bonds.append(Bond(a1, a2, order))
    else:
        # No bond info — infer from covalent radii
        for i in range(num_atoms):
            for j in range(i + 1, num_atoms):
                ai, aj = mol.atoms[i], mol.atoms[j]
                d = np.linalg.norm(ai.pos - aj.pos)
                if 0.4 < d < ai.covalent_radius + aj.covalent_radius + tol:
                    mol.bonds.append(Bond(i, j))

    return mol


# ═══════════════════════════════════════════════════════════════════════════
# CAD PRIMITIVES — no rotation math, uses Plane-based extrusion
# ═══════════════════════════════════════════════════════════════════════════

def _make_sphere(cq, center_mm, radius_mm):
    """Create a solid sphere at center_mm with given radius."""
    s = cq.Workplane("XY").sphere(radius_mm)
    return s.translate(cq.Vector(center_mm[0], center_mm[1], center_mm[2]))


def _make_cylinder(cq, start_mm, end_mm, radius_mm):
    """
    Create a solid cylinder from start_mm to end_mm.

    Uses CadQuery Plane-based extrusion: creates a workplane at start_mm
    with its normal pointing toward end_mm, draws a circle, and extrudes
    for the exact distance. NO rotation math involved.
    """
    start = np.asarray(start_mm, dtype=float)
    end = np.asarray(end_mm, dtype=float)
    direction = end - start
    length = np.linalg.norm(direction)
    if length < 1e-6:
        return None

    normal = cq.Vector(direction[0], direction[1], direction[2]).normalized()
    origin = cq.Vector(start[0], start[1], start[2])

    # xDir must be perpendicular to normal. Pick a stable reference.
    nv = direction / length
    if abs(nv[2]) < 0.9:
        ref = np.array([0, 0, 1])
    elif abs(nv[0]) < 0.9:
        ref = np.array([1, 0, 0])
    else:
        ref = np.array([0, 1, 0])
    x_dir_np = np.cross(nv, ref)
    x_dir_np = x_dir_np / np.linalg.norm(x_dir_np)
    x_dir = cq.Vector(x_dir_np[0], x_dir_np[1], x_dir_np[2])

    plane = cq.Plane(origin=origin, normal=normal, xDir=x_dir)
    cyl = cq.Workplane(plane).circle(radius_mm).extrude(length)
    return cyl


# ═══════════════════════════════════════════════════════════════════════════
# MODEL BUILDER
# ═══════════════════════════════════════════════════════════════════════════

def sphere_radius_mm(vdw_angstroms, scale, vdw_scale):
    """VdW radius → model sphere radius in mm."""
    return vdw_angstroms * vdw_scale * scale / 2.0


def tube_radius_mm(scale, bond_scale, override=None):
    """Compute bond tube radius from H VdW and scale factors."""
    if override is not None:
        return override
    return VDW_RADII["H"] * bond_scale * scale / 2.0


def validate_geometry(mol, scale, vdw_scale, bond_scale,
                      tube_radius_override=None):
    """
    Validate spatial contact between all spheres and tubes.
    Pure numpy — does NOT require CadQuery.
    """
    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    print("\n  ── Spatial contact validation ──")
    issues = 0

    for bond in mol.bonds:
        a1, a2 = mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]
        p1, p2 = a1.pos * scale, a2.pos * scale
        d = p2 - p1
        length = np.linalg.norm(d)
        if length < 0.01:
            print(f"  !! Zero-length bond {a1.element}{bond.atom1_idx}-"
                  f"{a2.element}{bond.atom2_idx}")
            issues += 1
            continue
        d_hat = d / length

        r1 = max(sphere_radius_mm(a1.vdw_radius, scale, vdw_scale),
                 t_r + MIN_EXCESS)
        r2 = max(sphere_radius_mm(a2.vdw_radius, scale, vdw_scale),
                 t_r + MIN_EXCESS)

        # Cylinder goes center-to-center (no extension)
        cyl_start = p1
        cyl_end = p2
        cyl_length = length

        if bond.order == 1:
            offsets = [(np.zeros(3), t_r, "single")]
        else:
            mr = t_r * 0.65
            od = t_r * 0.85
            if abs(d_hat[0]) < 0.9:
                perp = np.cross(d_hat, [1, 0, 0])
            else:
                perp = np.cross(d_hat, [0, 1, 0])
            perp = perp / np.linalg.norm(perp)
            offsets = []
            for k in range(bond.order):
                theta = math.pi * k if bond.order == 2 else \
                    2 * math.pi * k / bond.order
                off = perp * od * math.cos(theta)
                if bond.order > 1:
                    perp2 = np.cross(d_hat, perp)
                    off = off + perp2 * od * math.sin(theta)
                offsets.append((off, mr, f"multi-k{k}"))

        for off, cr, kind in offsets:
            for label, center, sph_r in [
                (f"{a1.element}{bond.atom1_idx}", p1, r1),
                (f"{a2.element}{bond.atom2_idx}", p2, r2),
            ]:
                axis_origin = cyl_start + off
                v = center - axis_origin
                proj = np.dot(v, d_hat)
                closest = axis_origin + proj * d_hat
                axis_dist = np.linalg.norm(center - closest)

                # For center-to-center: atom center is at proj=0 or proj=length
                # The cylinder endpoint coincides with atom center
                # Overlap = sphere extends past cylinder end along axis
                # Overlap depth along axis = sph_r (for centered bonds)
                #                          = sqrt(sph_r^2 - axis_dist^2) for offset
                if axis_dist < sph_r:
                    depth = math.sqrt(sph_r**2 - axis_dist**2)
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    # Also check sphere excess over tube
                    excess = sph_r - cr
                    status = "OK" if (in_range and excess > 0) else \
                             "TANGENT" if (in_range and excess <= 0) else \
                             "AXIS_SHORT"
                elif axis_dist < sph_r + cr:
                    depth = 0
                    in_range = (-0.01 <= proj <= cyl_length + 0.01)
                    status = "PARTIAL" if in_range else "MISS"
                else:
                    depth = 0
                    status = "NO_CONTACT"
                    in_range = False

                ok = status == "OK"
                if not ok:
                    issues += 1
                sym = "  " if ok else ">>"
                off_mag = np.linalg.norm(off)
                off_s = f"off={off_mag:.2f}" if off_mag > 0.01 else "ctr"
                print(f"  {sym} {a1.element}{bond.atom1_idx}-"
                      f"{a2.element}{bond.atom2_idx} -> {label}: "
                      f"ax_d={axis_dist:.3f} sph_r={sph_r:.2f} "
                      f"cyl_r={cr:.2f} proj={proj:.1f}/{cyl_length:.1f} "
                      f"depth={depth:.2f} excess={sph_r-cr:.2f} "
                      f"{off_s} {kind} [{status}]")

    if issues:
        print(f"\n  !! {issues} issues found !!")
    else:
        print(f"\n  All {len(mol.bonds)} bonds validated — "
              f"sphere_r > tube_r at every junction.")
    return issues


def build_model(mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                tube_radius_override=None, fillet_size=None,
                no_fillet=False, add_base=False, base_thickness=3.0,
                base_margin=5.0):
    """
    Per-atom hub architecture with OCCT rolling-ball fillets.

    Each atom produces exactly one hub solid:

        hub_A = sphere_A  union  tube(A->B1)  union  tube(A->B2)  union ...

    CadQuery .fillet() is then applied to the complete hub.  OCCT's
    BRepFilletAPI_MakeFillet finds every sphere-cylinder intersection
    edge on the hub and computes a rolling-ball fillet conforming to
    both surfaces simultaneously.  No torus approximations.

    Because each atom's sphere appears in exactly one hub, there are no
    duplicate-sphere artefacts.  Bond tubes appear in two hubs (one per
    endpoint) and overlap at the bond midpoint; this is harmless in a
    compound of overlapping solids.

    Junction geometry (overlap, angle) is computed analytically from the
    model parameters before any OCCT work, so problems are reported
    immediately rather than discovered in a post-hoc STEP probe.

    Returns a CadQuery Compound of hub solids.
    """
    import cadquery as cq

    t_r = tube_radius_mm(scale, bond_scale, tube_radius_override)
    if fillet_size is None:
        fillet_size = t_r * 0.3
    MIN_EXCESS = max(0.05, t_r * 0.01)

    def atom_r(atom):
        return max(sphere_radius_mm(atom.vdw_radius, scale, vdw_scale),
                   t_r + MIN_EXCESS)

    # ── Sizing and junction-geometry table ─────────────────────────────
    print(f"  Scale: {scale} mm/A  VdW: {vdw_scale}x  Bond: {bond_scale}x")
    print(f"  Tube radius: {t_r:.3f} mm   fillet: {fillet_size:.3f} mm")
    print()
    print(f"  {'Elem':4s}  {'sph_r':>7s}  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':4s}  {'-----':>7s}  {'-------':>8s}  {'-----':>7s}  ------")
    for elem in sorted(set(a.element for a in mol.atoms)):
        vdw = VDW_RADII.get(elem, DEFAULT_VDW_RADIUS)
        r   = max(sphere_radius_mm(vdw, scale, vdw_scale), t_r + MIN_EXCESS)
        ov  = r - t_r
        z   = math.sqrt(max(0.0, r*r - t_r*t_r))
        ang = math.degrees(math.asin(min(1.0, z / r)))
        st  = "ok" if ov >= 1.0 else ("marginal" if ov >= 0.3 else "GAP RISK")
        print(f"  {elem:4s}  {r:7.3f}  {ov:8.3f}  {ang:7.1f}  {st}")
    print()

    # ── Analytical gap check across all bonds ──────────────────────────
    gap_count = 0
    for bond in mol.bonds:
        for atom in (mol.atoms[bond.atom1_idx], mol.atoms[bond.atom2_idx]):
            if (atom_r(atom) - t_r) < 0.3:
                gap_count += 1
    if gap_count:
        print(f"  WARNING: {gap_count} junctions have overlap < 0.3 mm"
              f" -- reduce --bond-scale or raise --vdw-scale")
    else:
        print("  All junction overlaps >= 0.3 mm  (ok)")
    print()

    # ── Compute per-bond tube geometry (once per bond) ─────────────────
    # For double/triple bonds: parallel tubes offset from the bond axis.
    # Offsets are computed once from the canonical bond direction so both
    # endpoints receive identical offset vectors (no sign-flip confusion).
    #
    # atom_tubes[atom.index] = list of (start_mm, end_mm, cyl_radius)

    atom_tubes = {a.index: [] for a in mol.atoms}

    for bond in mol.bonds:
        a1  = mol.atoms[bond.atom1_idx]
        a2  = mol.atoms[bond.atom2_idx]
        p1  = np.asarray(a1.pos * scale, dtype=float)
        p2  = np.asarray(a2.pos * scale, dtype=float)
        vec = p2 - p1
        L   = float(np.linalg.norm(vec))
        if L < 0.01:
            continue
        d = vec / L

        if bond.order == 1:
            atom_tubes[a1.index].append((p1, p2, t_r))
            atom_tubes[a2.index].append((p2, p1, t_r))
        else:
            mr  = t_r * 0.65          # reduced radius per parallel tube
            od  = t_r * 0.85          # offset from bond axis
            ref = np.array([1.0, 0.0, 0.0]) if abs(d[0]) < 0.9 \
                  else np.array([0.0, 1.0, 0.0])
            u   = np.cross(d, ref);  u /= np.linalg.norm(u)   # first perp
            v   = np.cross(d, u)                                # second perp
            for k in range(bond.order):
                theta = (math.pi * k) if bond.order == 2 else \
                        (2.0 * math.pi * k / bond.order)
                off = od * (math.cos(theta) * u + math.sin(theta) * v)
                atom_tubes[a1.index].append((p1 + off, p2 + off, mr))
                atom_tubes[a2.index].append((p2 + off, p1 + off, mr))

    # ── Build hubs ─────────────────────────────────────────────────────
    print(f"  Building {len(mol.atoms)} hubs (sphere + tubes, then fillet)...")

    hub_solids  = []
    fillet_ok   = 0
    fillet_fail = 0

    for atom in mol.atoms:
        pos = np.asarray(atom.pos * scale, dtype=float)
        r   = atom_r(atom)

        # Start with the atom sphere
        hub = _make_sphere(cq, pos, r)

        # Fuse every bond tube into this hub
        for (start, end, cyl_r) in atom_tubes[atom.index]:
            cyl = _make_cylinder(cq, start, end, cyl_r)
            if cyl is None:
                continue
            try:
                hub = hub.union(cyl)
            except Exception as exc:
                print(f"    {atom.element}{atom.index}: tube union failed"
                      f" ({exc}) -- adding tube separately")
                hub_solids.append(cyl)

        # Apply OCCT rolling-ball fillet to the complete hub.
        # .fillet() finds all convex circular edges (sphere-cylinder
        # intersections) and blends them with a surface tangent to both
        # the sphere and the cylinder.
        if not no_fillet and fillet_size > 0 and atom_tubes[atom.index]:
            filleted = False
            for sz in [fillet_size, fillet_size * 0.5, fillet_size * 0.25]:
                try:
                    candidate = hub.fillet(sz)
                    if len(candidate.val().Faces()) > 0:
                        hub      = candidate
                        filleted = True
                        fillet_ok += 1
                        break
                except Exception:
                    pass
            if not filleted:
                fillet_fail += 1

        hub_solids.append(hub)

    if not no_fillet:
        print(f"  Fillets: {fillet_ok} ok, {fillet_fail} failed")
    print(f"  Compound: {len(hub_solids)} hub bodies")

    # ── Optional base plate ────────────────────────────────────────────
    if add_base:
        max_r = max(atom_r(a) for a in mol.atoms)
        bb_min, bb_max = mol.bounding_box()
        bmin = np.asarray(bb_min * scale, dtype=float)
        bmax = np.asarray(bb_max * scale, dtype=float)
        z_bot = float(bmin[2]) - max_r - 0.5
        w  = float(bmax[0] - bmin[0]) + 2 * base_margin + 2 * max_r
        dd = float(bmax[1] - bmin[1]) + 2 * base_margin + 2 * max_r
        cx = float(bmin[0] + bmax[0]) / 2.0
        cy = float(bmin[1] + bmax[1]) / 2.0
        base = (cq.Workplane("XY")
                .box(w, dd, base_thickness)
                .translate(cq.Vector(cx, cy, z_bot - base_thickness / 2.0)))
        try:
            base = base.edges("|Z").fillet(base_thickness * 0.4)
        except Exception:
            pass
        hub_solids.append(base)

    shapes = [s.val() if hasattr(s, 'val') else s for s in hub_solids]
    return cq.Compound.makeCompound(shapes)


def check_step_gaps(step_file, mol, scale=10.0, vdw_scale=1.0, bond_scale=1.0,
                    tube_radius_override=None, n_samples=12, probe_depth=0.5):
    """
    Analytical junction geometry check against a STEP file.

    Computes sphere-tube overlap and junction angle for every bond endpoint
    directly from the model parameters -- no point-in-solid probing needed.

    overlap  = sphere_radius - tube_radius
               (how deeply the tube is embedded in the sphere)
    angle    = arcsin(sqrt(sphere_r^2 - tube_r^2) / sphere_r)
               (the angle between the bond axis and the sphere surface
                at the junction circle; 90deg = ideal, 0deg = tangent)

    Both metrics are purely geometric and computed instantly.  The STEP
    file is loaded only to verify that the expected number of hub bodies
    is present.

    Flags:
      GAP      -- overlap < 0.3 mm  OR  angle < 10 deg
      MARGINAL -- overlap < 1.0 mm  OR  angle < 20 deg
    """
    import cadquery as cq

    print("=" * 70)
    print(f"JUNCTION GEOMETRY CHECK  ({step_file})")
    print("=" * 70)

    # Load STEP just to count bodies
    try:
        compound = cq.importers.importStep(str(step_file))
        n_bodies  = len(compound.solids().vals())
        expected  = len(mol.atoms)
        body_note = "ok" if n_bodies >= expected \
                    else f"WARNING expected >= {expected}"
        print(f"  STEP solid bodies: {n_bodies}  [{body_note}]")
    except Exception as exc:
        print(f"  Could not load STEP file: {exc}")

    t_r       = tube_radius_mm(scale, bond_scale, tube_radius_override)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    def atom_r(atom):
        return max(sphere_radius_mm(atom.vdw_radius, scale, vdw_scale),
                   t_r + MIN_EXCESS)

    print(f"  Tube radius: {t_r:.3f} mm")
    print()
    print(f"  {'Bond':22s}  {'end':>3s}  {'sph_r':>7s}"
          f"  {'overlap':>8s}  {'angle':>7s}  status")
    print(f"  {'----':22s}  {'---':>3s}  {'-----':>7s}"
          f"  {'-------':>8s}  {'-----':>7s}  ------")

    flags = []

    for bond in mol.bonds:
        a1    = mol.atoms[bond.atom1_idx]
        a2    = mol.atoms[bond.atom2_idx]
        r1, r2 = atom_r(a1), atom_r(a2)
        label  = f"{a1.element}{bond.atom1_idx}-{a2.element}{bond.atom2_idx}"

        for atom, r, end_lbl in [(a1, r1, "a1"), (a2, r2, "a2")]:
            if t_r >= r:
                print(f"  {label:22s}  {end_lbl:>3s}  DEGENERATE: tube_r >= sphere_r")
                flags.append((label, end_lbl, 0.0, 0.0, "GAP"))
                continue

            ov  = r - t_r
            z   = math.sqrt(r * r - t_r * t_r)
            ang = math.degrees(math.asin(min(1.0, z / r)))

            if ov < 0.3 or ang < 10.0:
                status = "GAP"
            elif ov < 1.0 or ang < 20.0:
                status = "MARGINAL"
            else:
                status = "ok"

            mark = "  <--" if status != "ok" else ""
            print(f"  {label:22s}  {end_lbl:>3s}  {r:7.3f}"
                  f"  {ov:8.3f}  {ang:7.1f}  {status}{mark}")

            if status != "ok":
                flags.append((label, end_lbl, ov, ang, status))

    print()
    if flags:
        print(f"  {len(flags)} junction(s) flagged:")
        for lbl, end, ov, ang, st in flags:
            print(f"    {lbl} ({end}):  overlap={ov:.3f} mm"
                  f"  angle={ang:.1f} deg  [{st}]")
    else:
        print("  All junctions ok.")
    print("=" * 70)


def export_model(shape, filepath, fmt="step"):
    """Export a CadQuery Shape (solid or compound) to STEP or STL."""
    import cadquery as cq
    if fmt in ("step", "stp"):
        cq.exporters.export(shape, filepath, exportType="STEP")
    elif fmt == "stl":
        cq.exporters.export(shape, filepath, exportType="STL",
                           tolerance=0.01, angularTolerance=0.1)
    else:
        raise ValueError(f"Unsupported format: {fmt}")


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(
        prog="mol2step.py",
        description=(
            "Generate solid BREP CAD files (STEP or STL) of ball-and-stick\n"
            "molecular models from molecular geometry files.\n\n"
            "Architecture: one hub solid per atom (sphere fused with all bond\n"
            "tubes), with OCCT rolling-ball fillets at every sphere-tube\n"
            "junction.  The result is a compound of overlapping hub solids\n"
            "that can be unioned in any STEP-capable CAD program."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=r"""
SCALE CONVENTION
  All distances are in mm.  Angstrom positions are multiplied by --scale.

  Atom sphere diameter  =  VdW_radius(A) * --vdw-scale * --scale
                        =  1 A  ->  1 cm diameter  (at defaults)

  Bond tube diameter    =  VdW_H(1.2 A) * --bond-scale * --scale
                        =  defaults give 8.4 mm diameter (bond-scale 0.7)

  Fillet radius         =  tube_radius * 0.3  (auto, or set with --fillet-size)

JUNCTION GEOMETRY
  At each sphere-tube junction the key metrics are:
    overlap  = sphere_radius - tube_radius  (tube embedded this far in sphere)
    angle    = arcsin(sqrt(r^2 - t^2) / r)  (surface meeting angle; 90=ideal)
  Both are printed at build time.  overlap < 0.3 mm or angle < 10 deg will
  produce visible seam artefacts.  Use --check-step to inspect after building.

INPUT FORMATS
  .mol / .sdf   MDL Molfile — explicit bond table, best choice
  .xyz          XYZ coordinates — bonds inferred from covalent radii + tolerance
  .pdb          PDB — CONECT records used; falls back to distance inference
  .cjson        Chemical JSON (Avogadro2 native format)

OUTPUT
  Default: <input_stem>.step  (STEP AP214, true BREP solid geometry)
  With --format stl: triangulated mesh for direct slicing

WORKFLOW
  1.  Obtain geometry:
        Avogadro2  ->  File > Export > Molecule (.cjson or .mol)
        PubChem    ->  Download > SDF (rename .sdf -> .mol, or use as-is)
        OpenBabel  ->  obabel input.pdb -O output.mol --gen3d

  2.  Generate STEP:
        python mol2step.py molecule.cjson -o molecule.step

  3.  Check for gaps (optional):
        python mol2step.py molecule.cjson --check-step molecule.step

  4.  Open in FreeCAD or OnShape:
        Part > Boolean > Union all bodies -> one solid
        Add fillets/chamfers, support struts, base plate as needed

  5.  Export STL / 3MF and slice in PrusaSlicer

EXAMPLES
  # Basic — defaults (vdw-scale 1.0, bond-scale 0.7)
  python mol2step.py caffeine.cjson -o caffeine.step

  # Smaller atoms and thinner bonds (good for larger molecules)
  python mol2step.py molecule.cjson --vdw-scale 0.7 --bond-scale 0.5

  # Custom fillet size
  python mol2step.py molecule.cjson --fillet-size 0.5

  # Print sizing table without building
  python mol2step.py molecule.cjson --info

  # Check junction geometry of an existing STEP file
  python mol2step.py molecule.cjson --check-step molecule.step

  # Add a base plate for bed adhesion
  python mol2step.py molecule.cjson --add-base --base-thickness 3.0

  # STL output (for direct slicing without CAD step)
  python mol2step.py molecule.cjson -o molecule.stl --format stl

  # Verbose bond/geometry validation
  python mol2step.py molecule.cjson --debug --info

PARAMETER GUIDE FOR 3D PRINTING
  Parameter        Default   Notes
  ───────────────────────────────────────────────────────────────────
  --scale          10.0      mm per Angstrom; increase for larger print
  --vdw-scale      1.0       atom sphere size multiplier
  --bond-scale     0.7       bond tube size multiplier (0.5-0.7 recommended)
  --fillet-size    auto      rolling-ball fillet radius; auto = tube_r * 0.3
  --bond-tolerance 0.4       Angstrom tolerance for bond inference (XYZ/PDB)

  Rule of thumb: bond-scale 0.5-0.7 keeps tubes noticeably thinner than atom
  spheres, which eliminates near-tangent junction artefacts.  The junction
  overlap and angle are printed at build time — look for "ok" on all elements.
""")

    # Positional
    p.add_argument("input",
                   help="Molecule file (.mol .sdf .xyz .pdb .cjson)")

    # Output
    p.add_argument("-o", "--output",
                   help="Output file path (default: <input_stem>.step or .stl)")
    p.add_argument("-f", "--format", choices=["step", "stp", "stl"],
                   default="step",
                   help="Output format: step (default), stp, or stl")

    # Scale
    p.add_argument("--scale", type=float, default=10.0,
                   help="Position scale in mm/Angstrom (default: 10.0)")
    p.add_argument("--vdw-scale", type=float, default=1.0,
                   help="Atom sphere radius multiplier (default: 1.0)")
    p.add_argument("--bond-scale", type=float, default=0.7,
                   help="Bond tube radius multiplier (default: 0.7; "
                        "keeps tubes thinner than H spheres to avoid gaps)")

    # Geometry overrides
    p.add_argument("--tube-radius", type=float, default=None,
                   help="Hard-override tube radius in mm (overrides --bond-scale)")
    p.add_argument("--fillet-size", type=float, default=None,
                   help="Rolling-ball fillet radius in mm "
                        "(default: tube_radius * 0.3)")
    p.add_argument("--no-fillet", action="store_true",
                   help="Skip filleting; export raw fused sphere+tube hubs")
    p.add_argument("--bond-tolerance", type=float, default=0.4,
                   help="Bond-inference distance tolerance in Angstroms "
                        "for XYZ/PDB files (default: 0.4)")

    # Base plate
    p.add_argument("--add-base", action="store_true",
                   help="Add a rectangular base plate for bed adhesion")
    p.add_argument("--base-thickness", type=float, default=3.0,
                   help="Base plate thickness in mm (default: 3.0)")
    p.add_argument("--base-margin", type=float, default=5.0,
                   help="Base plate margin beyond molecule extent in mm "
                        "(default: 5.0)")

    # Misc
    p.add_argument("--no-center", action="store_true",
                   help="Do not translate molecule to origin before building")
    p.add_argument("--info", action="store_true",
                   help="Print atom/tube sizing table and exit (no build)")
    p.add_argument("--debug", action="store_true",
                   help="Run verbose geometry validation (bond lengths, "
                        "sphere/tube clearances) and print report")

    # Gap check
    p.add_argument("--check-step", metavar="STEP_FILE",
                   help="Analyse junction geometry (overlap and angle) for "
                        "every bond endpoint in STEP_FILE and report; "
                        "also verifies body count.  No build needed.")
    p.add_argument("--probe-depth", type=float, default=0.5,
                   help=argparse.SUPPRESS)   # legacy, kept for compat
    p.add_argument("--probe-samples", type=int, default=12,
                   help=argparse.SUPPRESS)   # legacy, kept for compat

    args = p.parse_args()

    print(f"Loading: {args.input}")
    mol = load_molecule(args.input, args.bond_tolerance)
    if not args.no_center:
        mol.center_on_origin()

    t_r = tube_radius_mm(args.scale, args.bond_scale, args.tube_radius)
    MIN_EXCESS = max(0.05, t_r * 0.01)

    bb_min, bb_max = mol.bounding_box()
    ext = (bb_max - bb_min) * args.scale

    print(f"  Name: {mol.name}")
    print(f"  Atoms: {len(mol.atoms)}  Bonds: {len(mol.bonds)}")
    print(f"  VdW scale: {args.vdw_scale}x  Bond scale: {args.bond_scale}x")

    elems = sorted(set(a.element for a in mol.atoms))
    print(f"\n  {'Elem':4s}  {'VdW(A)':>6s}  {'r(mm)':>7s}  {'d(mm)':>7s}")
    print(f"  {'----':4s}  {'------':>6s}  {'-----':>7s}  {'-----':>7s}")
    for e in elems:
        vdw = VDW_RADII.get(e, DEFAULT_VDW_RADIUS)
        r = max(sphere_radius_mm(vdw, args.scale, args.vdw_scale),
                t_r + MIN_EXCESS)
        print(f"  {e:4s}  {vdw:6.2f}  {r:7.2f}  {r*2:7.2f}")
    print(f"  {'tube':4s}  {VDW_RADII['H']:6.2f}  {t_r:7.2f}  {t_r*2:7.2f}")
    print(f"\n  Bounding box: {bb_min.round(2)} to {bb_max.round(2)} A")
    print(f"  Model extent: {ext[0]:.1f} x {ext[1]:.1f} x {ext[2]:.1f} mm")

    if args.info and not args.debug:
        return

    if args.check_step:
        check_step_gaps(args.check_step, mol,
                        args.scale, args.vdw_scale, args.bond_scale,
                        args.tube_radius,
                        n_samples=args.probe_samples,
                        probe_depth=args.probe_depth)
        return

    if args.debug:
        validate_geometry(mol, args.scale, args.vdw_scale, args.bond_scale,
                          args.tube_radius)
        if args.info:
            return

    if not mol.bonds:
        print("\nERROR: No bonds found.  For XYZ/PDB files try "
              "--bond-tolerance 0.5")
        sys.exit(1)

    if args.output is None:
        stem = Path(args.input).stem
        args.output = f"{stem}.{'stl' if args.format == 'stl' else 'step'}"

    print(f"\nBuilding model...")
    shape = build_model(
        mol, args.scale, args.vdw_scale, args.bond_scale,
        args.tube_radius, args.fillet_size, args.no_fillet,
        args.add_base, args.base_thickness, args.base_margin)

    print(f"  Exporting: {args.output}")
    export_model(shape, args.output, args.format)
    print(f"Done -> {args.output}")
    print(f"\n  The STEP compound contains one hub solid per atom.")
    print(f"  To get a single solid in CAD:")
    print(f"    FreeCAD : select all bodies -> Part -> Boolean -> Union")
    print(f"    OnShape : select all -> Boolean -> Union")


if __name__ == "__main__":
    main()
